### ISSUE TITLE
Provide a figma

### ISSUE THREAD

**Issue by eznix86** [mrzachnugent/react-native-reusables#10]
I know it is not the scope of this repository, but most people in the mobile development space have a design system where they design beforehand what they expect as a design.

Turning the current components into figma components would be beneficial for the project.

**Comment by mrzachnugent** [comment]
It's great to see your enthusiasm for enhancing the repo.
 
To help me categorize bugs from requests I've set up the Discussions section. Please add your idea to the ["Ideas" category](https://github.com/mrzachnugent/react-native-reusables/discussions/categories/ideas) there and we'll close this issue. 

Thanks!
