### ISSUE TITLE
[ BUG ] form no work

### ISSUE THREAD

**Issue by jychen23333** [mrzachnugent/react-native-reusables#100]
**Describe the bug**

run [form.tsx](https://github.com/mrzachnugent/react-native-reusables/blob/main/apps/showcase/app/form.tsx)

'BottomSheetModalInternalContext' cannot be null!

This error is located at:
    in BottomSheetModal (created by BottomSheetModal)
    in Unknown (created by Combobox)

**Comment by mrzachnugent** [comment]
@jychen23333 

Is your root component wrapped with `BottomSheetModalProvider` from `@gorhom/bottom-sheet` like the [`app/_layout.tsx`](https://github.com/mrzachnugent/react-native-reusables/blob/main/apps/showcase/app/_layout.tsx) file in the showcase app?

**Comment by jychen23333** [comment]
It work, thanks so much!
