### ISSUE TITLE
[ Docs ] UI: Form

### ISSUE THREAD

**Issue by mrzachnugent** [mrzachnugent/react-native-reusables#104]

**Comment by andredewaard** [comment]
How are we supposed to use the form that is referred to in the demo?

**Comment by mrzachnugent** [comment]
Hey @andredewaard,

> **Warning**: Form and Form components are deprecated

You can use the [`packages/reusables/src/components/deprecated-ui/form.tsx`](https://github.com/mrzachnugent/react-native-reusables/blob/main/packages/reusables/src/components/deprecated-ui/form.tsx) as reference for components and [`apps/showcase/app/form.tsx`](https://github.com/mrzachnugent/react-native-reusables/blob/main/apps/showcase/app/form.tsx) for implementation.
