### ISSUE TITLE
Base Theme capabilities

### ISSUE THREAD

**Issue by eznix86** [mrzachnugent/react-native-reusables#11]
Providing a theme capabilities could help users just copy and paste what they need.

Similar to https://ui.shadcn.com/themes. We can provide already built-in themes, with specific colors and shapes.

One proposal for built-in themes are the base one (what we already have), and something _closer_ to Android Ecosystem (Material 2 or Material You) or iOS Ecosystem (Human Design Interface) in term of colors and shape.

I acknowledge that the current design system is not ever close to those ecosystem, but we can have base colors and shapes which can be closer to those Android and iOS. This can be platform specific in the long run. Example an app can have screens which can render some components for android only and iOS only.

**Comment by mrzachnugent** [comment]
_(copied from your previous issue)_

 It's great to see your enthusiasm for enhancing the repo.
 
To help me categorize bugs from requests I've set up the Discussions section. Please add your idea to the ["Ideas" category](https://github.com/mrzachnugent/react-native-reusables/discussions/categories/ideas) there and we'll close this issue. 

Thanks!
