### ISSUE TITLE
[ FEATURE ] CLI for generating of codes

### ISSUE THREAD

**Issue by glncy** [mrzachnugent/react-native-reusables#112]
**Is your feature request related to a problem? Please describe.**
I don't know if this is the problem but copy and pasting of codes maybe a little bit tedious to do specially if a component needs a component dependencies or primitive dependencies. Sometimes I run to errors because it needs some dependencies.

**Describe the solution you'd like**
Create a CLI to copy code. CLI should be able to Identify when one component needs dependencies and automatically copy and install.

**Additional context**
This project is amazing. Kudos to @mrzachnugent. I would like help also in maintaining this project. Since I am exploring creating CLIs and exploring to create and contribute to open source, Maybe I could try to create a CLI for this feature. Also if there's some needed help, I would like to give my time to help.

**Comment by mrzachnugent** [comment]
Hey @glncy,

I would love to have a CLI Tool. 

How would you go about it?

**Comment by mrzachnugent** [comment]
Feature in progress, should be available pretty soon.

For updates, you can check the feature branch until it is merged to main: https://github.com/mrzachnugent/react-native-reusables/tree/%40zach/feat-cli

**Comment by glncy** [comment]
Hi @mrzachnugent I just came from holiday. Just saw the new commit about CLI tool! It's great since you just use code from shadcn. My first thought was to build a CLI tool from scratch. I'll check on that and try it out and see what to improve on that. Thanks @mrzachnugent!
