### ISSUE TITLE
[ BUG ] Styles are not loaded

### ISSUE THREAD

**Issue by HugoBounoua** [mrzachnugent/react-native-reusables#117]
**Describe the bug**
The styles are not loaded, and all texts and labels are un-styled

**To Reproduce**
1. Install the Library
2. Add: `<TextClassContext.Provider value="text-red-500">
        <Text>The applied className is text-red-500</Text>
      </TextClassContext.Provider>`
3. Change anything in the style 
4. Nothing happens

**Expected behavior**
Style should be shown

**Platform (please complete the following information):**
 - Type: [Simulator, Device]
 - OS: iOS

**Additional context**
Installed everything twice, nothing is working.

**Comment by mrzachnugent** [comment]
@HugoBounoua Where are you importing `Text` from? 

Can you paste your implementation of the `Text` component?

**Comment by HugoBounoua** [comment]
@mrzachnugent Thank you for your quick response, I copied the `Text` implementation from the documentation:
```import * as Slot from '~/components/primitives/slot';
import { SlottableTextProps, TextRef } from '~/components/primitives/types';
import * as React from 'react';
import { Text as RNText } from 'react-native';
import { cn } from '~/lib/utils';

const TextClassContext = React.createContext<string | undefined>(undefined);

const Text = React.forwardRef<TextRef, SlottableTextProps>(
  ({ className, asChild = false, ...props }, ref) => {
    const textClass = React.useContext(TextClassContext);
    const Component = asChild ? Slot.Text : RNText;
    return (
      <Component
        className={cn('text-base text-foreground web:select-text', textClass, className)}
        ref={ref}
        {...props}
      />
    );
  }
);
Text.displayName = 'Text';

export { Text, TextClassContext };```

**Comment by mrzachnugent** [comment]
@HugoBounoua In your example:

```tsx
<TextClassContext.Provider value="text-red-500">
    <Text>The applied className is text-red-500</Text>
</TextClassContext.Provider>
```

Do you use `import { Text } from "react-native"` or `import { Text } from "~/components/ui/text"`?

**Comment by mrzachnugent** [comment]
I just noticed, there's an error on the `Screen.tsx` , `Parent.tsx` and `OtherParent.tsx` from https://rnr-docs.vercel.app/components/text/.

**Both** the `TextClassContext` and the `Text` should be imported from `~/components/ui/text`

**Comment by HugoBounoua** [comment]
@mrzachnugent One of my engineers got it working by downgrading to version "nativewind": "4.0.23". You might want to look into that. Thanks for your support, I hope that helps ;)
