### ISSUE TITLE
[ FEATURE ] Release to npm

### ISSUE THREAD

**Issue by rome-user** [mrzachnugent/react-native-reusables#119]
I would like to use this library, but it's a bit awkward to use because of having to copy-paste code. I would like to have something versioned; not necessarily following semver.

If this is not something you are willing to do, then is there specific advice for treating this code like a library? For instance, should we prefer

a. create package in private registry
b. simply use `file:/path/to/rnr` in our package.json
c. a different method for consuming this library

Thanks

**Comment by mrzachnugent** [comment]
Hey @rome-user,

Given the results from https://github.com/mrzachnugent/react-native-reusables/discussions/49, it seems the direction to go would be with a CLI tool like on `ui/shadcn` (ex: https://ui.shadcn.com/docs/components/accordion#installation).

The [discussions](https://github.com/mrzachnugent/react-native-reusables/discussions) are always open for anyone to voice their opinions. You are very welcome.
