### ISSUE TITLE
Proposal for rn-reusables-cli

### ISSUE THREAD

**Issue by eznix86** [mrzachnugent/react-native-reusables#12]
I looked into how `shadcn-ui` works, it basically have a JSON to pull from:

https://ui.shadcn.com/registry

We can have a second repository to keep this json list from github, we can get inspiration from https://github.com/shadcn-ui/ui/blob/main/packages/cli/src/index.ts

**Comment by mrzachnugent** [comment]
_(copied from your previous issue)_

 It's great to see your enthusiasm for enhancing the repo.
 
To help me categorize bugs from requests I've set up the Discussions section. Please add your idea to the ["Ideas" category](https://github.com/mrzachnugent/react-native-reusables/discussions/categories/ideas) there and we'll close this issue. 

Thanks!
