### ISSUE TITLE
[ BUG ] copy button doesn't work on the primitives/types docs page

### ISSUE THREAD

**Issue by tctrautman** [mrzachnugent/react-native-reusables#121]
**Describe the bug**
The copy button for the code block doesn't copy code to the clipboard the same way that it does for other pages:

https://rnr-docs.vercel.app/primitives/types/

Also - excellent job with this repo.  Very impressive work and super helpful.

**Comment by mrzachnugent** [comment]
@tctrautman Thanks for contributing! It is now fixed.
