### ISSUE TITLE
[ BUG ] TypeScript not working

### ISSUE THREAD

**Issue by AprilNEA** [mrzachnugent/react-native-reusables#123]
**Describe the bug**
My TypeScript won't work anyway.

**To Reproduce**
Copying the components as per the documentation, I make sure all the copied paths are okay

**Expected behavior**
Type inference should work properly

**Screenshots**
<img width="1589" alt="image" src="https://github.com/mrzachnugent/react-native-reusables/assets/37977109/7d7eb571-0749-47de-b8b2-597f493bbbcd">

<img width="876" alt="image" src="https://github.com/mrzachnugent/react-native-reusables/assets/37977109/79b40c86-7074-4e20-a22d-32d88219192c">

**Platform (please complete the following information):**
 - OS: MacOS
 - IDE: WebStorm
 - Nodejs: v20
 - TypeScript: 5.4.3

**Additional context**
Here is my tsconfig
```
{
  "extends": "expo/tsconfig.base",
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "jsx": "preserve",
    "lib": [
      "dom",
      "esnext"
    ],
    "moduleResolution": "node",
    "noEmit": true,
    "skipLibCheck": true,
    "resolveJsonModule": true,
    "target": "esnext",
    "allowJs": true,
    "forceConsistentCasingInFileNames": true,
    "esModuleInterop": true,
    "module": "esnext",
    "isolatedModules": true,
    "strict": true,
    "baseUrl": "./src",
    "types": [
      "nativewind/types"
    ],
    "paths": {
      "@/*": [
        "./*"
      ]
    }
  },
  "include": [
    "app.d.ts",
    "**/*.ts",
    "**/*.tsx"
  ],
}

```

**Comment by AprilNEA** [comment]
Seems related to: https://github.com/redwoodjs/redwood/issues/5104
When I add the following lines to `tsconfig.json`, the type works correctly.
```json
"compilerOptions": {
    "paths": {
      "react": [
        "./node_modules/@types/react"
      ]
    }
}
```

**Comment by mrzachnugent** [comment]
I had this issue when updating my packages with `npx expo install --fix`. I had to delete my `node_modules` and install them again to fix it.
