### ISSUE TITLE
[ BUG ] Cli is broken

### ISSUE THREAD

**Issue by ig4e** [mrzachnugent/react-native-reusables#127]
**Describe the bug**

**To Reproduce**
1. type `npx @react-native-reusables/cli@latest add collapsible` or `npx @react-native-reusables/cli@latest add checkbox`

**Expected behavior**
It should install the component

**Screenshots**
![image](https://github.com/mrzachnugent/react-native-reusables/assets/50212311/142d1209-4982-48a7-9151-79b4437f936a)

**Platform (please complete the following information):**
 - Type: Vscode pwsh
 - OS: Windows

**Additional context**
It seems like the files is downloaded correctly but for some reason It just doesn't work
![image](https://github.com/mrzachnugent/react-native-reusables/assets/50212311/8b517cfc-b2ff-44cb-b81d-8be2358c4dea)

**Comment by mrzachnugent** [comment]
@ig4e Thank you for contributing with this issue.

I updated the cli to version `0.0.13` with the fix. You should be able to use `npx @react-native-reusables/cli@latest add collapsible checkbox`

Let me know if it works for you now.

**Comment by ig4e** [comment]
@mrzachnugent Thanks for the quick reply I will try and let you know!!

**Comment by ig4e** [comment]
@mrzachnugent It seems to be fixed but there's an issue which I feel should be discussed in another issue but it tends to ignore the --overwrite when I use the multi select

![image](https://github.com/mrzachnugent/react-native-reusables/assets/50212311/55fc298a-c522-4b7f-8546-ccc2ad3fe52b)

![image](https://github.com/mrzachnugent/react-native-reusables/assets/50212311/1ec584dd-92d6-40cd-be6b-28b5b3414c1a)

**Comment by mrzachnugent** [comment]
@ig4e Great! I will close this issue.

For the --override flag, could you open another issue? Also, if you could, mention if you would rather the flag override all files that already exist or prompt you for every file that it can override.

**Comment by ig4e** [comment]
> @ig4e Great! I will close this issue.
> 
> For the --override flag, could you open another issue? Also, if you could, mention if you would rather the flag override all files that already exist or prompt you for every file that it can override.

Sure!, I have opened a new issue at #128 .
