### ISSUE TITLE
[ BUG ] Cli overwrite

### ISSUE THREAD

**Issue by ig4e** [mrzachnugent/react-native-reusables#128]
**Describe the bug**
Currently the `--overwrite` flag doesn't work on single installation or multiple installations

**To Reproduce (Single installation)**
1. Run `npx @react-native-reusables/cli@latest add tooltip --overwrite`

**Expected behavior**
It should overwrite the components/primitives and not log that the file was skipped.

While this lib is inspired by Shadcn/ui, I guess settling with a similar behavior would be easy to pick up

Case 1: when the user installs already installed components, it will prompt the user asking if he wants to overwrite or no

![image](https://github.com/mrzachnugent/react-native-reusables/assets/50212311/516b8b00-106d-4880-b954-ec6a6e219368)
![image](https://github.com/mrzachnugent/react-native-reusables/assets/50212311/081a9488-3c91-4241-bfda-ded361e8f6d7)

Case 2: when the user installs already installed components using the --overwrite flag, it will overwrite any existing components without prompting each time

![image](https://github.com/mrzachnugent/react-native-reusables/assets/50212311/0afda1b7-f4c3-41d7-8afc-b08be3008888)

**Screenshots**

* Single installation:

![image](https://github.com/mrzachnugent/react-native-reusables/assets/50212311/150a6e23-1079-4f6c-b16b-c8e7437ab496)

The outlined lines in red display incorrect behavior (Saying to run with --overwrite even if I'm using the --overwrite flag)
While the lines outlined in green are shared, I'm not really sure what the behavior should be.

* Multiple installations:

The above also applies here when installing multiple components/primitives 

![image](https://github.com/mrzachnugent/react-native-reusables/assets/50212311/4fbafe29-833e-4aa1-8845-d0dee027a69d)

**Platform (please complete the following information):**
 - Type: Cli
 - OS: Windows PWSH, Windows WSL (Ubuntu)

**Additional context**
I hope I did a good job covering this issue, excuse my English and Thanks for making this!

**Comment by mrzachnugent** [comment]
@ig4e Thank you!. You did a great job covering the issue and your english was very good.

I just updated the latest version. When passing the `--overwrite` flag, it will now prompt you for every existing file to ensure it is overwriting the wanted files.
