### ISSUE TITLE
[ FEATURE ] Bottom sheet

### ISSUE THREAD

**Issue by pixelkoduje** [mrzachnugent/react-native-reusables#134]
Where is bottom sheet Reusable in component ui?

**Comment by mrzachnugent** [comment]
Hey @pixelkoduje 

The bottom-sheet is still a work-in-progress. For now, you can use the bottom-sheet for iOS and Android from the ['deprecated-ui' folder](https://github.com/mrzachnugent/react-native-reusables/blob/main/packages/reusables/src/components/deprecated-ui/bottom-sheet.native.tsx)
