### ISSUE TITLE
Bug: not being able to run the demo project

### ISSUE THREAD

**Issue by a0m0rajab** [mrzachnugent/react-native-reusables#137]
**Describe the bug**
I went through the readme to test and check the project, but was not able to run the demo and the project got stuck here is the error: 

Web: 
![image](https://github.com/mrzachnugent/react-native-reusables/assets/18273833/d4509fd2-e51b-49ab-8a9b-99baad0a3c82)

for android I got another issue, might open anothor issue for that. 

**To Reproduce**
1. go to the readme
2. apply the read me steps
2. try to open web or android

**Expected behavior**
was expected the app to run without any issues.

**Comment by mrzachnugent** [comment]
Hi @a0m0rajab, 
I see that you posted here: https://github.com/mrzachnugent/react-native-reusables/issues/131. If you are using windows, it seems like this might be duplicate of the issue above.

Is this a different issue?

**Comment by a0m0rajab** [comment]
Hi @mrzachnugent yeah, its the same issue they mentioned there, but that issue was related to "setting up to existing project", and this is just for running the demos. I felt it worth to have it as new issue since you have answered the question in the previous issue.

**Comment by mrzachnugent** [comment]
@a0m0rajab I changed the title of the other PR so it includes this issue. Thanks!

**Comment by a0m0rajab** [comment]
Thank you for that! @mrzachnugent
