### ISSUE TITLE
[ BUG ] Nested text with different font size getting cut off

### ISSUE THREAD

**Issue by dhatGuy** [mrzachnugent/react-native-reusables#141]
**Describe the bug**
When a text is nested inside another text component, the text with the biggest size gets cut off at the top. For example, a `Text` nested inside `H1`, the `H1` gets cut off at the top.

**To Reproduce**
```
import { H1, P } from "~/components/ui/typography";
import { Text } from "~/components/ui/text";

      <View className="max-w-lg">
        <H1>
          The Rainbow <Text>Forest Adventure</Text>
        </H1>
        <View className="p-1.5" />
        <P>
          Once upon a time, <H1>in a magical forest</H1>, there lived a curious rabbit named
          Whiskers. Whiskers loved exploring and discovering new things every day.
        </P>
        <View className="p-3" />
      </View>
```

**Expected behavior**
The nested `Text` should inherit the `H1` styles and not no text should get cut off if different font sizes are used

**Screenshots**
![Screenshot_2024-05-05-21-42-53-423](https://github.com/mrzachnugent/react-native-reusables/assets/51405947/94125d6e-f2eb-40ac-bb50-ad9754e1453c)

**Platform (please complete the following information):**
 - Type: Device
 - OS: Android

**Additional context**

**Comment by mrzachnugent** [comment]
Hi @dhatGuy, from a semantics point of view you probably shouldn't put an h1 in a p tag. For this reason, I will keep it this way in react-native-reusables.

For your use case, you can remove the `text-base` class from the `<P/>` component to fix the nested `<H1/>` text from being cut off. The `text-base` class also sets `line-height: 1.5rem` which cuts off the `<H1 />` text that overflows the line-height.
