### ISSUE TITLE
[ BUG ] dark modifier on native

### ISSUE THREAD

**Issue by younes200** [mrzachnugent/react-native-reusables#146]
**Describe the bug**
It is likely a nativewind issue, but it is strange since `dark:` is used on other components.

works fine with` ios:` `android:` : <View className="h-20 w-20 bg-primary ios:bg-destructive"/>
**To Reproduce**

1. Start project
2. Run :
```
import * as React from 'react';
import { View } from 'react-native';

export default function Screen() {

  return (
    <View className='flex-1'>
      <View className="h-20 w-20 bg-primary dark:bg-destructive"/>
    </View>
  );
}

```

**Expected behavior**

**Screenshots**

<img width="1599" alt="Screenshot 2024-05-13 at 20 17 52" src="https://github.com/mrzachnugent/react-native-reusables/assets/198514/4f2321dc-9791-4489-9fa1-61dbc4e29049">

**Platform (please complete the following information):**
 - Type: Browser, Simulator, Emulator, Device
 - OS: iOS, Android

**Additional context**
- Expo : ~50.0.17
- nativewind ^4.0.1

**Comment by mrzachnugent** [comment]
Hey @younes200, yes this is a Nativewind issue. I see that you created one there as well so I will close this one.

I've had a similar issue that linked to the the web's generated css. If it's the same thing, when you close your instance of metro, and restart it. Then it should work. Classes that did not already exist when starting the terminal will not show up on the web.
