### ISSUE TITLE
[ BUG ] Error during rendering Select component.

### ISSUE THREAD

**Issue by przemekscibiorek** [mrzachnugent/react-native-reusables#147]
**Describe the bug**
After installing select component and adding example code from docs I receive error 
```
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports

Check the render method of `TriggerNativeSelect`.
```

**Expected behavior**
App should render without errors

**Platform (please complete the following information):**
 - Type: Simulator,
 - OS: iOS 15

**Additional context**

**Comment by cedricchavaudra** [comment]
Good morning,

I encountered exactly the same problem when trying to test the Select component.

**Comment by cedricchavaudra** [comment]
Same problem also with the "Accordion" component, I don't know if it's related

**Comment by mrzachnugent** [comment]
Hey @cedricchavaudra  @przemekscibiorek,

This is an issue related to the Icon that your component is using. The icon is not exported from your icons file so it causes this error.

It is something that will be solved by the CLI in the future. For now, you can follow these steps to fix this issue: https://github.com/mrzachnugent/react-native-reusables/issues/142#issuecomment-2098634170
