### ISSUE TITLE
[ BUG ] RangeError: Maximum call stack size exceeded when running starter-base templare

### ISSUE THREAD

**Issue by issam-seghir** [mrzachnugent/react-native-reusables#149]
![image](https://github.com/mrzachnugent/react-native-reusables/assets/74573675/11624760-1048-44e6-b0e6-3fda1905493b)

**Comment by mrzachnugent** [comment]
Hi @issam-seghir,

Can you provide a minimal reproduction repo as I am unable to reproduce this error?

You can also have a look at the comments from this passed expo issue: https://github.com/expo/expo/issues/8578 It might contain the solution you are looking for.

**Comment by issam-seghir** [comment]
The issue arises when utilizing Node v LTS 20.10.0. However, upon upgrading to the most recent LTS version, 20.13.1, my problem is successfully resolved.
