### ISSUE TITLE
How to open select menu programmatically?

### ISSUE THREAD

**Issue by useEffects** [mrzachnugent/react-native-reusables#151]
```jsx
 <Select defaultValue={{ value: 'apple', label: 'Apple' }} open={true}>
 ```
 i can also confirm `open` doesnt seem to do anything, but setting `open={false}` would disable the functionality. Also `defaultOpen` doesnt seem to do anything

**Comment by mrzachnugent** [comment]
@useEffects Unfortunately it is not possible at the moment. It slipped my attention. The reason is that components like `Select` and `Dropdown`'s position on the screen is calculated on press.

What is your exact use case for opening the menus programmatically?

**Comment by mrzachnugent** [comment]
@useEffects I just updated the ui and primitive components like Select and Dropdown Menu. Once you update your components, you can follow the instructions here: https://rnr-docs.vercel.app/getting-started/common-patterns/#programmatically-showing-and-hiding-components.

If you run into another issue, please open a new one. Thanks!
