### ISSUE TITLE
[ BUG ] Overlapping options in combobox

### ISSUE THREAD

**Issue by przemekscibiorek** [mrzachnugent/react-native-reusables#153]
**Describe the bug**
After implementing a combobox in my application, when the bottom sheet is displayed, the elements in the list overlap.

**To Reproduce**
`<FormField
                control={form.control}
                name="type"
                render={({ field }) => (
                  <FormCombobox
                    isLoading={isLoading}
                    label={t("TYPE")}
                    placeholder={t("TYPE_PLACEHOLDER")}
                    //description="More important than your skills."
                    items={data?.map(
                      (country) =>
                        ({
                          value: country.id,
                          label: country.name,
                        } as unknown as ComboboxOption)
                    )}
                    {...field}
                  />
                )}
              />`

**Expected behavior**
Items are in seperate lines.

**Screenshots**
![image](https://github.com/mrzachnugent/react-native-reusables/assets/123740917/5c321c39-496c-44c1-9020-df17f27f7dd0)

**Platform (please complete the following information):**
 - Type: Simulator, Physical
 - OS: iOS

**Comment by mrzachnugent** [comment]
Hey @przemekscibiorek Thanks for contributing! You can find the fix in the comment above.

**Comment by przemekscibiorek** [comment]
Thanks a lot. Works like a charm!
