### ISSUE TITLE
[ BUG ] CLI command not add aspect-ratio/ to primitives/ and progress.tsx to /ui

### ISSUE THREAD

**Issue by KhoaLee** [mrzachnugent/react-native-reusables#155]
**Describe the bug**
I've had followed the step to implement react-native-reusables using the command
 
`npx @react-native-reusables/cli@latest add <component name>`

At first, my assumption is to let the <component name> empty so that it will behave like the CLI of shadcn will let me select all components. I did that and recognize that aspect-ratio folder in components/primitives and progress.tsx in components/ui were not added. 

**To Reproduce**
1. Start with `npx @react-native-reusables/cli@latest add`
2. Press "Shift + A" to select all components from CLI 
3. Press "Enter" to add all components
3. Go to the components/primitives -> no aspect-ratio component folder  in this directory but aspect-ratio.tsx was added in the components/ui directory
4. Go to the components/ui -> no progress.tsx file
5. Go to the components/primitives -> no progress component folder 

**Expected behavior**

Running CLI with: `npx @react-native-reusables/cli@latest add` and follow step 2 and 3 above
- The aspect-ratio folder for components/primitives should be added with the `npx @react-native-reusables/cli@latest add`
- The progress.tsx file should be added to the components/ui directory
- The progress folder should be added to the components/primitives directory

**Platform (please complete the following information):**
 - Type:  Browser, Simulator, Emulator
 - OS:  iOS
 - Browser chrome

**Additional context**

I am using the t3-turbo to create a monorepo and try to use the react-native-reusables as a shared UI library for expo and nextjs. 

** Temporary solution **

** The solution **

- For aspect-ratio component folder in components/primitive. I copied the folder from react-native-reusables repo to my local components/primitives
- For progress.tsx, I first installed with `npx expo install @radix-ui/react-progress` then follow the manual guide to copy the .tsx and folder component to my local

**Comment by mrzachnugent** [comment]
Hey @KhoaLee  thanks for your contribution! I've released a new version of the CLI, all because of your detailed issue report.
