### ISSUE TITLE
[ FEATURE ] Select Autocomplete

### ISSUE THREAD

**Issue by modbender** [mrzachnugent/react-native-reusables#156]
I have a huge list of cities for user to choose from, don't want people to use location, instead choose a city.

Is there no Autocomplete Select implementation in React Native Reusables?

**Comment by mrzachnugent** [comment]
Hi @modbender,

There was a select autocomplete but it is now deprecated. You can find it in: [`packages/reusables/src/components/deprecated-ui/combobox.tsx`](https://github.com/mrzachnugent/react-native-reusables/blob/main/packages/reusables/src/components/deprecated-ui/combobox.tsx). 

> **Warning**: Use with caution
