### ISSUE TITLE
"Not implemented for web yet. Check `bottom-sheet.tsx` for more info. Why?

### ISSUE THREAD

**Issue by Zakisb** [mrzachnugent/react-native-reusables#157]
I successfully copied the calendar from the github repo but I got ""Not implemented for web yet. Check `bottom-sheet.tsx` for more info." why ? isn't the component ready yet for expo app?

**Comment by mrzachnugent** [comment]
Hey @Zakisb, as stated in the `bottom-sheet.tsx` file, the dependency used by the component [`react-native-bottom-sheet`](https://github.com/gorhom/react-native-bottom-sheet) is not available for web yet.

According to the [this discussion](https://github.com/gorhom/react-native-bottom-sheet/discussions/1125), web support should be introduced in v5. The current version is v4.6.3.

**Comment by andredewaard** [comment]
How would we trigger the BottomSheet to open if we would only use this on native devices? im not planning to support web.

**Comment by mrzachnugent** [comment]
@adebayoileri Looks very cool! If I were to add a "Community" (or something like that) section to the README with a link to your universal-bottom-sheet, is that something that you would be OK with?

Example: 

```md
# Community

- [universal-bottom-sheet](https://github.com/adebayoileri/universal-bottom-sheet) by [adebayoileri](https://github.com/adebayoileri)
```

**Comment by adebayoileri** [comment]
Sure @mrzachnugent, I'm completely fine with that. Thank you.
