### ISSUE TITLE
[ BUG ] Progress component (progress.tsx) missing "& indicatorClassname?: string" via CLI installed

### ISSUE THREAD

**Issue by KhoaLee** [mrzachnugent/react-native-reusables#158]
**Describe the bug**
Installed component via CLI: `npx @react-native-reusables/cli@latest add progress`. In the file `progress.tsx` of the `components/ui` directory, the 
`React.forwardRef<React.ElementRef<typeof ProgressPrimitive.Root>, React.ComponentPropsWithoutRef<typeof ProgressPrimitive.Root> {} `  missing the `indicatorClassName?: string`. 

**To Reproduce**
1. Start the `npx @react-native-reusables/cli@latest add progress` to install the `progress` component
2. Go to the `components/ui`
2. Click on `progress.tsx` file
3. Look for 
<img width="745" alt="image" src="https://github.com/mrzachnugent/react-native-reusables/assets/33981342/29a6fb3a-77bc-4d29-94d4-85de9c4128e8">
4. There is a missing prop `& {indicatorClassName?: string}`

**Screenshots**

- From the `packages\components\ui` directory on the react-native-reusables repo
<img width="763" alt="image" src="https://github.com/mrzachnugent/react-native-reusables/assets/33981342/4914617a-8375-48d4-a4e0-af026210d0f2">

- From installation via CLI
<img width="745" alt="image" src="https://github.com/mrzachnugent/react-native-reusables/assets/33981342/d946cdcb-389b-4828-b3d7-21e0f44a425f">

- From the `apps/starter-base/components/ui` directory on the react-native-reusables repo
<img width="842" alt="image" src="https://github.com/mrzachnugent/react-native-reusables/assets/33981342/f302dff3-2539-40a3-a94d-77dd1f23d56c">

**Platform (please complete the following information):**
 - Type: Browser, Simulator, Emulator, Device
 - OS: iOS
 - Browser: chrome

**Additional context**
- This is not a critical bug, I can contribute and help to fix this in my spare time @mrzachnugent

**Comment by mrzachnugent** [comment]
This was including in the last CLI release. Please make sure to use the "@latest" with `npx @react-native-reusables/cli@latest add`
