### ISSUE TITLE
[ FEATURE ] rocketicon support 

### ISSUE THREAD

**Issue by Ashraf-Ali-aa** [mrzachnugent/react-native-reusables#162]
Adding support for rocket icons would make it's easier to work with icons via tailwind https://github.com/rocketclimb/rocketicons

**Comment by mrzachnugent** [comment]
@Ashraf-Ali-aa I am unfamiliar with that library. From a quick look, I didn't see how to use the custom css variables. Do you know how this would be done?

Do you know how it affects the build size of the application? There seems to be a lot of icon libraries. Lucide Icons offers a way to use a generic icon. We do not use it since it would significantly increase the build size of the application. 

> Source https://lucide.dev/guide/packages/lucide-react-native#one-generic-icon-component

**Comment by Ashraf-Ali-aa** [comment]
@mrzachnugent have a look at the demo on the website https://rocketicons.io/en It just using the tailwind CSS values, regarding build size I think they are using es6 imports

**Comment by mrzachnugent** [comment]
@Ashraf-Ali-aa From the example, I don't see an `icon-primary-foreground-lg` like example where the icon uses the custom css variables.

Do you use this library?

**Comment by Ashraf-Ali-aa** [comment]
> @Ashraf-Ali-aa From the example, I don't see an `icon-primary-foreground-lg` like example where the icon uses the custom css variables.
> 
> Do you use this library?
 

unless I misunderstood, 
you can extend the tailwind config to add the custom variable like https://rocketicons.io/en/docs/getting-started then use the variable for the icon, I want to use it in conjunction with this library

**Comment by mrzachnugent** [comment]
Hey @Ashraf-Ali-aa,

Thank you for your suggestion to switch to a different icon library. After careful consideration, I have decided to stick with the current library. Switching would introduce several breaking changes, and it’s relatively straightforward for you to use the icon library of your choice within your implementation. After using the `@react-native-reusables/cli`, if the component uses an icon, remove the icon file that the cli created and replace the icon in you `components/ui` file.

I appreciate your understanding and contribution.
