### ISSUE TITLE
Select Item overflowing with no option to scroll. (Android only)

### ISSUE THREAD

**Issue by dhruvwill** [mrzachnugent/react-native-reusables#163]
There is a limit on the number of children that can be added to select content function. After the limit is crossed the options are chopped down, and we can't even scroll the view content box. while the ios has a native select which is capable of rendering multiple items, the list items are getting truncated on android.

**To Reproduce**
1. Create a sample expo project.
2. use "select" from rnr
3. add at least 10 items in select item view.

**Expected behavior**
The list items should be chopped down, and you shouldn't be able to scroll and see the truncated options.

**Screenshots**
[untitled.webm](https://github.com/mrzachnugent/react-native-reusables/assets/90319162/964d0040-e1d5-4742-9675-2ca962465f4a)

**Comment by ariburaco** [comment]
I am having this issue also. Is there way to add a scrolling option to the list view?

**Comment by umutbozdag** [comment]
Okay I have found the solution, wrap your SelectGroup within ScrollView with max-h property and set onStartShouldSetResponder func to **true**. 

Example:

```
<SelectContent
          insets={contentInsets}
          className="w-[250px]"
        >
          <ScrollView className="max-h-80">
            <SelectGroup
              onStartShouldSetResponder={() => true}
            >
              <SelectLabel>Activity Types</SelectLabel>
              {activityTypes.map((type) => (
                <SelectItem
                  key={type.value}
                  label={type.label}
                  value={type.value}
                >
                  {type.label}
                </SelectItem>
              ))}
            </SelectGroup>
          </ScrollView>
        </SelectContent>
```

**Comment by DanSytnikov** [comment]
I am facing the same issue. Unfortunately, @umutbozdag 's advice doesn't work for me :(
As a temporary solution, you can use DropdownMenu instead of Select. For example:
` <DropdownMenuContent insets={contentInsets} className="w-full">
          <FlatList
            data={data}
            style={{
              maxHeight: 300,
            }}
            keyExtractor={({ key}) => key}
            renderItem={({ item: { label, value } }) => (
            // ur code here
            
            ....
            `

**Comment by mrzachnugent** [comment]
## Fixes

I added an example in the showcase app which require changes for the Scrollable Content issue: https://github.com/mrzachnugent/react-native-reusables/commit/60ca07a4d571df1ba9cc79844cf654181d2b4a9d

#### Item overflow
A couple of options:
- Adjust the bottom inset for the `SelectContent`'s inset prop. 
```tsx
<SelectContent insets={{
    top: insets.top,
    bottom: Platform.select({android: insets.bottom  + 24, default: insets.bottom}),
    left: 12,
    right: 12,
  }} />
```
- Set the side of the `SelectContent` to the top.  
```tsx
<SelectContent side="top" />
```

#### Scrollable content
- In the root `_layout.tsx`, move the `PortalHost` component up one line so that it is a child of `GestureHandlerRootView`
```diff
      <GestureHandlerRootView style={{ flex: 1 }}>
        // ...
+        <PortalHost />
      </GestureHandlerRootView>
-     <PortalHost />
```
- Import `ScrollView` from react-native-gesture-handler, wrap the content of `SelectContent` within the `ScrollView` and set a max height to the `ScrollView`
```diff
+ import { ScrollView } from 'react-native-gesture-handler';
     // ...
  <SelectContent insets={contentInsets} className='w-[250px]'>
+   <ScrollView className='max-h-32'>
      // ...
+   </ScrollView>
  </SelectContent>
```
- For the web component: In the `~components/ui/select.tsx` file, in the `SelectContent` component, remove the `View` that wraps the `SelectPrimitive.Viewport`
```diff
-           <View>
              <SelectPrimitive.Viewport
                className={cn(
                  'p-1',
                  position === 'popper' &&
                    'h-[var(--radix-select-trigger-height)] w-full min-w-[var(--radix-select-trigger-width)]'
                )}
              >
                {children}
              </SelectPrimitive.Viewport>
-           </View>
```
