### ISSUE TITLE
Dropdown menu position with new Architecture enable

### ISSUE THREAD

**Issue by ahmadbakhshi** [mrzachnugent/react-native-reusables#164]
**Describe the bug**
After enabling new Architecture with expo, dropdown menu position is off if the screen has Appbar, it works fine when `headerShown` is false 
I have tried with and without **SafeAreaProvider**

**To Reproduce**
1. enable new architecture by installing `expo-build-properties` and updating app.json
  ```json
"plugins": [
       ...,
      [
        "expo-build-properties",
        {
          "ios": {
            "newArchEnabled": true
          },
          "android": {
            "newArchEnabled": true
          }
        }
      ]
    ],
```

**Screenshots**
With Appbar:
![image](https://github.com/mrzachnugent/react-native-reusables/assets/17783744/3449f6db-ea39-4638-800a-db607f296193)

Without Appbar
![image](https://github.com/mrzachnugent/react-native-reusables/assets/17783744/3fa76320-9762-41ff-a852-cd93ae03b7ce)

**Platform (please complete the following information):**
 - Type: Simulator
 - OS:iOS

**Comment by mrzachnugent** [comment]
@ahmadbakhshi Can you try again with the @rn-primitives or update your `useRelativePosition.tsx` from https://github.com/roninoss/rn-primitives/blob/main/packages/hooks/src/useRelativePosition.tsx ?

The main difference is that dimensions are calculated with the "screen" instead of with the "window"

**Comment by ahmadbakhshi** [comment]
@mrzachnugent It works fine now. Thank you

**Comment by ahmadbakhshi** [comment]
@mrzachnugent It works fine now. Thank you.
