### ISSUE TITLE
[FEATURE]: Add new bare example

### ISSUE THREAD

**Issue by a0m0rajab** [mrzachnugent/react-native-reusables#167]
**Is your feature request related to a problem? Please describe.**
I worked on new bare example for the rnr that uses the latest `npx create expo` which came with tabs supported by default and all the goods with `expo-navigation` I was wondering if it worth to add this to the apps as example of bare project with no much updates and changes so people can start from there? 

Here is the repo: 
https://github.com/a0m0rajab/rnr-base-bare

**Comment by mrzachnugent** [comment]
@a0m0rajab Very nice! I can add it to the README.

How about a format like:

## Community templates
- [RNR Base Bare](https://github.com/a0m0rajab/rnr-base-bare) by [a0m0rajab](https://github.com/a0m0rajab): _short description goes here_

Could you provide the short description you would like me to put?

**Comment by a0m0rajab** [comment]
@mrzachnugent that would be great, I will appreciate it! thanks for the suggestion.
