### ISSUE TITLE
[ FEATURE ]: improved input 

### ISSUE THREAD

**Issue by a0m0rajab** [mrzachnugent/react-native-reusables#168]
**Is your feature request related to a problem? Please describe.**
How do you feel about adding right/left icons to the input field so that the user can play with them and add that? I have seen this as example in the elements library and thought to bring it here. 

Inspired by: https://reactnativeelements.com/docs/components/input

Having label as well would be great!

**Comment by mrzachnugent** [comment]
Hi @a0m0rajab Unfortunately inputs with icons is out of the ui/shadcn paradigm (see: https://ui.shadcn.com/docs/components/input) so I cannot add it to this project. If I were to do it, I would wrap the input with a View, add the Icon as a child of that View with a position of absolute, then depending on the side you want to put it add padding to the input according the size of the icon.

For the label, you can check out: https://rnr-docs.vercel.app/components/label/

**Comment by a0m0rajab** [comment]
@mrzachnugent thanks for that I did not check the shadcn/ui paradigm when I wrote this. but it make sense now! yes, my go to solution was to use a wrapper for the label and the icons!
