### ISSUE TITLE
[ BUG ] Styles not loading

### ISSUE THREAD

**Issue by manticarodrigo** [mrzachnugent/react-native-reusables#169]
I updated to latest (rn-primitives) and overwrote components with cli and now I see the following problems:
1. Progress bars are not rendering
2. Dialog and popover backgrounds missing
3. Dialog is positioned top left of the screen

**Screenshots**
![Screenshot 2024-06-25 at 10 12 54 AM](https://github.com/mrzachnugent/react-native-reusables/assets/17787530/a2ee375f-b75f-4f57-9335-e39d59a6e7e6)

**Platform**
- iOS simulator

**Additional Context**
I tried starting project with `expo start -c` and rebuilding node modules, but no dice.

**Comment by mrzachnugent** [comment]
@manticarodrigo At first glance, this looks like a NativeWind issue. The icons are. If deleting the `/node_modules`, re-installing the dependencies, and starting with `expo start -c` doesn't work, you can try to update your expo related dependencies with `npx expo install --fix`.

If that doesn't help, could you provide a minimal-reproduction-repo?

**Comment by manticarodrigo** [comment]
Thanks for helping out. When I change ProgressPrimitive.Root for View, then all the styles apply fine. For more context, it's in a pnpm monorepo and its adding the primitives to the root node_modules. I'll keep trying to fix but nothing yet.

**Comment by mrzachnugent** [comment]
@manticarodrigo Given that you are using a monorepo, you might need to update your `tailwind.config.js` to have a path for your "content" to your "node_modules". See the tailwind.config.js example from the tailwind docs: https://tailwindcss.com/docs/content-configuration#working-with-third-party-libraries

**Comment by manticarodrigo** [comment]
@mrzachnugent I see what my issue is but don't know how to solve it. Maybe you have some insight here.

I was able to get styles working by moving the primitives back into my codebase. I noticed that `Animated.View` was still not working however (a 3rd-party lib). It seems I need to wrap components coming from node modules with `cssInterop` in order for it to work. Am I setting up something incorrectly that requires me to wrap any non-core components with cssInterop?

**Comment by mrzachnugent** [comment]
@manticarodrigo It's hard to say without a minimal reproduction repo.

Applying the `cssInterop` function depends on how the package was built. In theory you shouldn't need to wrap the primitives or an `Animated.View` with that function.

You can take the [`apps/showcase`](https://github.com/mrzachnugent/react-native-reusables/tree/main/apps/showcase) as an example. In the `tailwind.config.js`, there is a `content` item that is `'./node_modules/@rnr/**/*.{ts,tsx}'`. This is where the components from the monorepo live for this app. There is no need to use `cssInterop` for the UI components.

You can also take the [`packages/reusables`](https://github.com/mrzachnugent/react-native-reusables/tree/main/packages/reusables) as the example for the components library. This is where the `@rn-primitives` are used and there is no need for `cssInterop` on the primitives or on `Animated.View`s.

**Comment by manticarodrigo** [comment]
@mrzachnugent its something else. The components are in my expo project (not importing from a separate ui package in monorepo). If I try to remove tailwind from `ProgressPrimitive.Root` and use style prop instead, it's still not rendering. Something about the bundler is not working correctly.

**Comment by mrzachnugent** [comment]
@manticarodrigo Unfortunately without a minimal reproduction repo I cannot help you.

If you are still running into this issue, please open a new issue with a minimal reproduction repo.

Thanks

**Comment by manticarodrigo** [comment]
I was able to solve it by pinpointing the dependencies that rnr uses. I format my packages to use exact versions, but rnr needs `@react-navigation/native`, `nativewind`, and `react-native-css-interop` to be the `~` versions used in the showcase example.
