### ISSUE TITLE
[ BUG ] Select item content showing under modal

### ISSUE THREAD

**Issue by HemalSPatel** [mrzachnugent/react-native-reusables#172]
**Describe the bug**
When using the RNR Select component inside of a react native modal (or a tamagui dialog) the content shows up underneath hence the user can't see or interact with it. (I have tried changing the z-index of all the select components to 200000 and it still did not show on top)

**To Reproduce**
1. Create a new Expo Project
2. Put Select in a react native modal
2. Click on the Select

**Expected behavior**
Select content should be above the modal

**Screenshots**
<img width="340" alt="Screenshot 2024-06-27 at 5 26 30 PM" src="https://github.com/mrzachnugent/react-native-reusables/assets/95436169/7f5af887-c593-4796-9a87-8731a29748b6">

**Platform (please complete the following information):**
 - Expo Go
 - OS: iOS, Android

**Additional context**

**Comment by mrzachnugent** [comment]
Hey @HemalSPatel, have you tried this: https://rnr-docs.vercel.app/getting-started/common-patterns/#a-portal-component-inside-a-presentation-modal-screen ?

**Comment by HemalSPatel** [comment]
I tried that but it did not solve the problem.

**Comment by mrzachnugent** [comment]
@HemalSPatel Could you provide a minimal reproduction repo?

**Comment by mrzachnugent** [comment]
Here is a working example: https://github.com/mrzachnugent/react-native-reusables/blob/main/apps/showcase/app/modal.tsx

**Comment by mrzachnugent** [comment]
Closed to to inactivity. If this issue persists please open a new issue with a **minimal reproduction repo**

**Comment by lessp** [comment]
Were you able to solve this @HemalSPatel? Facing the same issue.

**Comment by lessp** [comment]
Did you solve this @HemalSPatel? I'm facing the same issue and the workaround doesn't seem to fix it for me, unless you need to apply it directly to a `Stack.Screen` and not a descendent.

**Comment by phanuelmutuma** [comment]
> Hey @HemalSPatel, have you tried this: https://rnr-docs.vercel.app/getting-started/common-patterns/#a-portal-component-inside-a-presentation-modal-screen ?

@lessp I managed to make it work using the above.  Have you added the portal host name to the SelectContent

**Comment by mathritter** [comment]
Should this work on a modal component?
