### ISSUE TITLE
[ FEATURE ] React Native Web config for other bundlers like vite?

### ISSUE THREAD

**Issue by imWildCat** [mrzachnugent/react-native-reusables#173]
**Is your feature request related to a problem? Please describe.**

Tamagui has great docs about bundlers in addition to Metro: <https://tamagui.dev/docs/guides/vite>

Does rn-resuables have a plan to add docs for other bundlers?

**Comment by mrzachnugent** [comment]
Hey @imWildCat, no plans to add docs for other bundlers at the moment.
