### ISSUE TITLE
Button: Span or Div should not be allowed

### ISSUE THREAD

**Issue by shawnmclean** [mrzachnugent/react-native-reusables#174]
For the button component, on the web, it might not be a good idea to render the text to a div.

I'm playing around with this package and building a simple counter, when clicking the button fast, it starts to highlight the text inside it.

You can see that here (click really quickly):
ie. https://rnr-showcase.vercel.app/button

So I did some searching to see if this is a thing and came up on this SO post:
reference: https://stackoverflow.com/questions/12982269/is-it-semantically-incorrect-to-put-a-div-or-span-inside-of-a-button

If I use `asChild`, nothing gets rendered in the button:

```
<Button className="m-2" onPress={handleCounter}>
   <Text asChild>Increase</Text>
 </Button>
```

Any way to bypass this or fix this?

**Comment by mrzachnugent** [comment]
@shawnmclean Thanks for opening this issue. Here is the fix: https://github.com/mrzachnugent/react-native-reusables/commit/13eb6eb9bd46c4805422588e113e6544ad2cb6a7
