### ISSUE TITLE
Switch [Reanimated] Tried to synchronously call a non-worklet function `t1` on the UI thread

### ISSUE THREAD

**Issue by ahmadbakhshi** [mrzachnugent/react-native-reusables#179]
**Describe the bug**
Just by adding switch to my component (with and without controller). getting this error.
I'm not sure if it's related, but it happened after I removed primitives folder and moved to @rn-primitives

**To Reproduce**
```jsx
<Switch checked={false} onCheckedChange={() => {}} />
```

**Screenshots**
![simulator_screenshot_0A792474-3C51-43C9-8E10-E1E45C797966](https://github.com/mrzachnugent/react-native-reusables/assets/17783744/0cc5d9cd-fee2-423f-9917-81440eab8b4a)

**Platform (please complete the following information):**
 - OS: iOS

**Comment by mrzachnugent** [comment]
Hey @ahmadbakhshi, unfortunately I am unable to reproduce this error. In a new project I used `npx @react-native-reusables/cli add switch` to add the switch and it works as expected.

<img width="442" alt="Screenshot 2024-07-14 at 1 09 13 PM" src="https://github.com/user-attachments/assets/239df59f-b37a-47db-965f-dae4423b654a">

If you are still experiencing this issue, please open a new issue with a **minimal reproduction repo**

**Comment by ahmadbakhshi** [comment]
Seems like enabling react compiler could cause this error.
this an many other errors using react-native-web
