### ISSUE TITLE
[ BUG ] Component's className is not applied for frameworkless React Native projects

### ISSUE THREAD

**Issue by kaichaosun** [mrzachnugent/react-native-reusables#180]
**Describe the bug**

The className on DialogContent in the dialog component  is not working, for react native (without expo), iOS.
Also the DialogTitle and Dialog are not applied by its own styling.

<img width="407" alt="image" src="https://github.com/mrzachnugent/react-native-reusables/assets/10568673/a8aafeac-23a7-4a50-83cf-9b37ae5783a2">

**Comment by megacherry** [comment]
this is also happening in next.js (Label classnames). But i think the problem lies with rn-primitives (https://github.com/roninoss/rn-primitives).

**Comment by mrzachnugent** [comment]
Hey @kaichaosun, this seems like it might be a NativeWind/metro/babel issue which decides how the code should be transformed. From the primitives side, it lets the project that calls the primitive decide these things.

As a workaround, you can use the `cssInterop` function on the primitives that you want to add a className. For example:
```tsx
import * as LabelPrimitive from '@rn-primitives/label';
import {cssInterop} from 'nativewind';
cssInterop(LabelPrimitive.Text, {className: 'style'});
```

https://www.nativewind.dev/v4/guides/third-party-components#handling-multiple-props-with-similar-properties
