### ISSUE TITLE
bottom sheet vs native 

### ISSUE THREAD

**Issue by ImamJanjua** [mrzachnugent/react-native-reusables#181]
What is the difference between the native bottom sheet and the normal ones in the deperacted ui

**Comment by ImamJanjua** [comment]
And for the form component like this is also desperacted because I think it has some components build into it like calendar or bottomsheet which is only build for native. But shouldn't form be a valid component if theses native components which are not available for web get removed. Like in the original schadcn the form component also does not have things like a formCalendar, or Formselect directly in the form coomponent. But only things related to form  are included and the components like a select will be placed into the formControl so it flexible.

**Comment by mrzachnugent** [comment]
Hey @ImamJanjua, yes the bottom sheet component is deprecated which means it is no longer recommended for use and may be removed in the future. The "normal" one is the web implementation and it shows an alert if you try to use it as the underlying library is not ready for web.

Same thing for the Form component. There are challenges in React-Native which made implementing it like the web more challenging and maybe impossible.

You can use the code for inspiration for your own components but keep in mind that they are deprecated.
