### ISSUE TITLE
Toast Example

### ISSUE THREAD

**Issue by ImamJanjua** [mrzachnugent/react-native-reusables#183]
Hi I saw that there is a primitive for toast but I cannot find any example of usage or the component in the docs.

**Comment by ImamJanjua** [comment]
any updates on that?

**Comment by maxilie** [comment]
I think that might be a remnant of a deprecated component that relies on a separate library for react-native toasts.

https://github.com/mrzachnugent/react-native-reusables/blob/main/packages/reusables/src/components/deprecated-ui/toast.tsx

**Comment by ImamJanjua** [comment]
I mean technically I can use it but I would really prefer to use the component by the author of this lib. @mrzachnugent and thoughts on that

**Comment by mrzachnugent** [comment]
@ImamJanjua There is an example of using the primitive here: https://github.com/mrzachnugent/react-native-reusables/blob/main/apps/showcase/app/toast/toast-primitive.tsx

As I am now maintaining 4 open source projects, this toast component is low priority. If you need one soon, I suggest using `react-native-toast-message` or building your own with the toast primitive.
