### ISSUE TITLE
[ BUG ] Separator import fails with ts(4023)

### ISSUE THREAD

**Issue by ar3s3ru** [mrzachnugent/react-native-reusables#185]
**Describe the bug**

The `Separator` component code is not valid, as it emits `ts(4023)` error.

**To Reproduce**
1. Install `@rn-primitives/separator`
2. Import the `Separator` component into `~/components/ui/separator.tsx`
2. Check TS Server output

**Expected behavior**
No issue in the imported code from `tsc` or TS Server.

**Additional context**
The issue happens due to `SeparatorRootProps` not being exported, but the type being used in the type definition of the component regardless:

```tsx
const Separator = React.forwardRef<
  React.ElementRef<typeof SeparatorPrimitive.Root>,
  React.ComponentPropsWithoutRef<typeof SeparatorPrimitive.Root> // <-- here specifically
>(({ className, orientation = 'horizontal', decorative = true, ...props }, ref) => (
```

The solution would be to export `SeparatorRootProps` together with the `Root` element.

**Comment by kerimovok** [comment]
I don't have this error on WebStorm (TypeScript 5.3.3)

**Comment by mrzachnugent** [comment]
@ar3s3ru Please provide an minimal reproduction repo as I am unable to reproduce.

**Comment by mrzachnugent** [comment]
Closed due to inactivity
