### ISSUE TITLE
button not losing active state

### ISSUE THREAD

**Issue by ImamJanjua** [mrzachnugent/react-native-reusables#186]
https://github.com/user-attachments/assets/ebe7f226-e857-4190-956e-879d6750462a
I have changed nothing in the component but the active affect will not go away

**Comment by mrzachnugent** [comment]
@ImamJanjua Can you provide a minimal reproduction repo?

I am unable to reproduce your issue.

https://github.com/user-attachments/assets/a3a201fa-5363-4c0e-b6cd-e7d4d9e946ca

**Comment by ImamJanjua** [comment]
@mrzachnugent nevermind  just needed to clean the cache. But could u maybe response to the issue related to toast example

**Comment by ImamJanjua** [comment]
@mrzachnugent Now I am very sure the issue is related to the component. Check out the clip. So as u can see here I started the app with cleaned cache. So button works fine, until I added just to call the func on press where i get many error and this press affect

https://github.com/user-attachments/assets/a300f943-893a-48ee-ae46-cff1cc8b5141

**Comment by ImamJanjua** [comment]
<img width="1325" alt="Screenshot 2024-07-27 at 17 49 48" src="https://github.com/user-attachments/assets/2f04ee73-227f-4663-8221-d32a5bd1beca">
<img width="1341" alt="Screenshot 2024-07-27 at 17 50 16" src="https://github.com/user-attachments/assets/0527e762-e102-4545-a71c-0b5387387dcb">
<img width="1324" alt="Screenshot 2024-07-27 at 17 52 48" src="https://github.com/user-attachments/assets/619234d8-351e-4fe9-81fe-5527a1718de0">
