### ISSUE TITLE
Error: You attempted to set the key `width` with the value `0` on an object that is meant to be immutable and has been frozen.

### ISSUE THREAD

**Issue by callum-gander** [mrzachnugent/react-native-reusables#19]
Hey,

Try to integrate this whole package into my app while it's still being developed, got some components working fine but others not so much. This type of error is a persistent issue. For some, like Accordion, it'll load correctly with Expo Go on the first load, but on subsequent refreshes, you'll get get an error just like this pop up. But for other components, like Tabs, as below, it won't even reach first load without throwing an error. See the error below

My hunch is that this is to do with what you say in the README about some components being compatible with Expo Go and some not being. Do you know how to resolve it? Can you possibly confirm why this is an issue? Also, could you let tell me what components you know aren't compatible with Expo Go? 

Amazing work by they way! Thanks for starting building something like this for RN!

```
ERROR  Error: You attempted to set the key `width` with the value `0` on an object that is meant to be immutable and has been frozen.

This error is located at:
    in CssInteropComponent (created by Alert)
    in Alert (created by CustomTabsView)
    in RCTView (created by View)
    in View (created by CSSInterop.View)
    in CssInteropComponent (created by CustomTabsView)
    in RCTView (created by View)
```

**Comment by mrzachnugent** [comment]
Hi @callum-gander,

All components are compatible with Expo Go at the moment. I'm pretty sure I got that error at some point but I don't remember what caused it. 

Could you provide a minimal reproduction repo?

**Comment by mrzachnugent** [comment]
Thanks for providing a reproduction repo.

The issue comes from conditionally setting the shadow in the `<Card />`'s style. Ideally, the shadow would be set with NativeWind but I'm having trouble with the shadow. So for now, a ViewStyle with have to do,

Here is how you can fix it:

```jsx
const Card = React.forwardRef<
  React.ElementRef<typeof View>,
  Omit<React.ComponentPropsWithoutRef<typeof View>, "style"> & {
    style?: ViewStyle
  }
>(({ className, style: styleProp, ...props }, ref) => {
  const { colorScheme } = useColorScheme()
  const [style, setStyle] = React.useState<ViewStyle>(styleProp ?? {})

  React.useEffect(() => {
    setStyle(
      StyleSheet.flatten([
        colorScheme === "dark" ? styles.shadowDark : styles.shadowLight,
        styleProp,
      ])
    )
  }, [styleProp, colorScheme])

  React.useEffect(() => {}, [])
  return (
    <View
      ref={ref}
      className={cn(
        "rounded-lg border border-border bg-card px-0.5 py-2",
        className
      )}
      style={style}
      {...props}
    />
  )
})

Card.displayName = "Card"
```

**Comment by callum-gander** [comment]
This correctly fixes this card issue, but this is still an issue on basically every component for me, for example, within that same repo if you setup a `Select` component, this error persists, as it does with basically every single component I used. Any advice? Am I just going to have to go through every component and do this?

**Comment by mrzachnugent** [comment]
With the `Select` component, I'm not sure about that one. The original issue comes from conditionally setting the light/dark shadows outside of a useEffect.

I updated all of the components with this issue in: https://github.com/mrzachnugent/react-native-reusables/commit/cfba30e6b52ef72465668fe13ff1c4ab3d4fd602

If you are getting the same error message with the shadow being conditionally rendered in a useEffect, please open a new issue with a minimal reproduction repo.

**Comment by callum-gander** [comment]
This error seemingly isn't completely solved. I duplicated the same page as in that repo with the cards but with alll the code in that PR of yours, which works fine if it's the first page that loads when expo go is used. But if you have a second page in `_layout/tabs` then the same error as initially encountered will occur. Are there other places within the codebase where you're explicitly modifying the width?
