### ISSUE TITLE
[ FEATURE ]  icons library

### ISSUE THREAD

**Issue by iCodePup** [mrzachnugent/react-native-reusables#193]
Lucide icons are beautiful but i am already facing an issue using this package, because there is no more brand icons allowed.
For instance its not possible to find popular icons for social login  

Solutions:

- Include others icons library that including this brand icons like simple icons
- Add a documentation how to add others icons to lucide (svg)
- Add a documentation how to use others icon library allowing className.
Thanks

**Comment by mrzachnugent** [comment]
If Lucide Icons do not meet your needs, by all means, use any Icon library you need. The idea for react-native-reusables is that it is a starting point for your projects. It is not a perfect solution for all use cases. For those reason, I will not be adding documentation on how to use other libraries.

If you use another icon library like `expo-vector-icons`, you can use the `iconWithClassName` function the same way. See https://github.com/mrzachnugent/react-native-reusables/blob/main/packages/reusables/src/lib/icons/Activity.tsx for reference.
