### ISSUE TITLE
[ BUG ] Button not losing active state

### ISSUE THREAD

**Issue by ImamJanjua** [mrzachnugent/react-native-reusables#194]
@mrzachnugent I had created similar issue in the past but Now I am very sure the issue is related to the component. Check out the clip. So as u can see here I started the app with cleaned cache. So button works fine, until I added just to call the func on press where i get many error and this press affect

https://github.com/user-attachments/assets/164497e4-9e5e-4c9f-9860-e3cfa930727b

**Comment by ImamJanjua** [comment]
<img width="390" alt="Screenshot 2024-07-27 at 17 58 59" src="https://github.com/user-attachments/assets/c6d953b8-cfdd-4f08-a072-eb404bccab87">
<img width="401" alt="Screenshot 2024-07-27 at 17 59 13" src="https://github.com/user-attachments/assets/53a0d72d-12e9-4987-8d8c-b1b455f001e4">
<img width="436" alt="Screenshot 2024-07-27 at 17 59 34" src="https://github.com/user-attachments/assets/02c866e0-4d4c-41cd-be19-e57ed570f8d6">
<img width="479" alt="Screenshot 2024-07-27 at 17 59 46" src="https://github.com/user-attachments/assets/fb7e41c7-e6c7-4e48-8c74-de30a08801bc">

**Comment by ImamJanjua** [comment]
@mrzachnugent any though on that

**Comment by mrzachnugent** [comment]
Hey @ImamJanjua, as mentioned in https://github.com/mrzachnugent/react-native-reusables/issues/186, I would need a minimal reproduction repo to look into this since I am not able to reproduce it on my side.

**Comment by mrzachnugent** [comment]
@ImamJanjua After some investigation, if you replace your `test` function with:
```tsx
  async function test() {
    const res = await fetch("https://icanhazdadjoke.com/", {
      method: "GET",
      headers: {
        "Content-Type": "application/json",
        Accept: "application/json",
      },
    });
    const jsonData = await res.json();
    console.log(jsonData);
  }
  ```
  
The warning goes away. So it seems the experimental api directory feature is causing this warning. I also noticed that if you keep using the api directory but you removed all of the button classNames that start with `web:` then it would also remove the warning.

I would suggest creating an issue for expo-router using the same repo as the minimal reproduction repo.
