### ISSUE TITLE
[ FEATURE ] replace lucide with react-native-iconify

### ISSUE THREAD

**Issue by RajeshPandey057** [mrzachnugent/react-native-reusables#198]
**Is your feature request related to a problem? Please describe.**
Lucide icons are get but as noted by many others, limited. I managed to get ```iconWithClassName``` function working with 'react-native-iconify' It also has lucide icons bundled in along with 150K other icons so should not be a change in any component. The major benefit would be that if we migrate to 'react-native-iconify', we can have one root 'Iconify' component exported once and no need to have 100 component for 100 icons. As it also uses 'react-native-svg' under the hood, things and styling will remain same as currently with lucide icons.

**Describe the solution you'd like**
Replace all lucide icons with Iconify in code and replace 'icons' folder generated by cli with one single file as shown below,
```typescript
import { cssInterop } from 'nativewind';
import { Iconify } from 'react-native-iconify';

cssInterop(Iconify, {
	className: {
		target: 'style',
		nativeStyleToProp: {
			color: true,
			opacity: true,
		},
	},
});
export { Iconify };
```

**Describe alternatives you've considered**
Current icon set (lucide) but found it limited.

**Additional context**
Library link: https://github.com/oktaysenkan/react-native-iconify
Iconify link: https://iconify.design/
Iconify icon-set link: https://icon-sets.iconify.design/?category=General

**Comment by mrzachnugent** [comment]
Unfortunately, this will not be added into this project. This is meant to be a starting point for your project and you are heavily encouraged to modify it in your project for your needs.

This would introduce breaking changes, it would force all users to learn the Iconify library and handle its specific rules like https://github.com/oktaysenkan/react-native-iconify?tab=readme-ov-file#iconify-icon-prop-must-be-a-string-literal, and it creates a greater distance between shadcn/ui and this project.

Feel free to open a discussion for other who might be interested in using this icon lib instead.
