### ISSUE TITLE
[ BUG ] UI inconsistencies and styling issues on Android

### ISSUE THREAD

**Issue by helix-77** [mrzachnugent/react-native-reusables#199]
**Describe the bug**
UI elements are displaying inconsistently on Android on the first launch(when i do clean prebuild), while working just fine on iOS. These issues resolve themselves after reloading the app few times.

**Expected behavior**
UI elements should display correctly with proper padding, spacing, and text rendering on first launch. See the screenshots to get an idea. 

**Screenshots**
first run
![a2](https://github.com/user-attachments/assets/94a0234c-5e2f-4910-9121-85388a0c7dae)

after few reloads
![a1](https://github.com/user-attachments/assets/7aef1aef-e2a5-41f4-8271-e898e85859fa)

first run
![b2](https://github.com/user-attachments/assets/80db4c8b-6b55-4d24-959e-c200d3f954c9)

after few reloads
![b1](https://github.com/user-attachments/assets/c25c128a-c62c-4b84-9e56-54c37712bb81)

**Here, Button text aren't properly printed. Padding and margins are not working properly for view and other elements. Popover styles are also affected**

**To Reproduce**
1. Prebuild the app 
2. launch the app on an Android

**Comment by helix-77** [comment]
`npx expo start --clear` worked. Margin and padding related inconsistencies are fixed. But **RNR** button still not showing full button text. See the screenshot bellow.
![Screenshot 2024-08-01 045537](https://github.com/user-attachments/assets/466e9e6e-88be-4cd8-9546-1bb84fcee906)




here's the minimal repro for the screenshot. : https://github.com/helix-77/repro-rnr

**Comment by mrzachnugent** [comment]
@helix-77 At first glance, it seems like everything works:

<img width="1682" alt="Screenshot 2024-08-01 at 7 35 00 PM" src="https://github.com/user-attachments/assets/63a4bddc-9469-4450-835f-4b317ce9e331">

However, when I tried changing anything in the app, it did not show on the Android side. Once I manually reloaded the app (by pressing "r" in the terminal), I would see the changes. This is a NativeWind issue but it should be fixed really soon: https://github.com/nativewind/nativewind/issues/600#issuecomment-2192912430 .
