### ISSUE TITLE
[ FEATURE ] Support for shadcn/ui charts

### ISSUE THREAD

**Issue by armandokun** [mrzachnugent/react-native-reusables#203]
There are plenty of chart libraries for React Native, but none that suits and looks better than [shadcn/ui charts](https://ui.shadcn.com/charts)

Is there a timeline for when the charts will be introduced? 

I've also tried [react-native-gifted-charts](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts) and Victory Charts before but none match the quality of shadcn.

**Comment by mrzachnugent** [comment]
Hi @armandokun 

Due to a recent scope update this feature request is no longer within our current focus. See https://github.com/mrzachnugent/react-native-reusables/discussions/229, for more details.

Thanks for understanding!
