### ISSUE TITLE
[ FEATURE ] Need Form component

### ISSUE THREAD

**Issue by useEffects** [mrzachnugent/react-native-reusables#204]

**Comment by RWOverdijk** [comment]
I don't understand this issue, isn't there already form stuff? I can see it in the docs and in the showcase

**Comment by useEffects** [comment]
@RWOverdijk where?

**Comment by RWOverdijk** [comment]
https://rnr-showcase.vercel.app/form

**Comment by useEffects** [comment]
@RWOverdijk Its a deprecated component

**Comment by RWOverdijk** [comment]
What do you mean? Form itself doesn't have a component. All the fields and such are in there (input, checkbox, radio). Forms don't have styles so I don't think I understand what you are looking for 😄

**Comment by grdmno** [comment]
Help, scroll not working

from [Form.tsx](https://github.com/mrzachnugent/react-native-reusables/blob/main/apps/showcase/app/form.tsx)
```jsonc
const emails = [
  { value: 'tom@cruise.com', label: 'tom@cruise.com' },
  { value: 'napoleon@dynamite.com', label: 'napoleon@dynamite.com' },
  { value: 'kunfu@panda.com', label: 'kunfu@panda.com' },
  { value: 'bruce@lee.com', label: 'bruce@lee.com' },
  { value: 'harry@potter.com', label: 'harry@potter.com' },
  { value: 'jane@doe.com', label: 'jane@doe.com' },
  { value: 'elon@musk.com', label: 'elon@musk.com' },
  { value: 'lara@croft.com', label: 'lara@croft.com' },
  ... 50+ more
];
```


```javascript
                </SelectTrigger>
                <SelectContent insets={contentInsets} style={{ width: selectTriggerWidth }}>
                  <SelectGroup>
                  // Not scrolling
                    <ScrollView ref={emailScrollRef}>
                      {emails.map((email) => (
                        <SelectItem key={email.value} label={email.label} value={email.value}>
                          <Text>{email.label}</Text>
                        </SelectItem>
                      ))}
                    </ScrollView>
                  </SelectGroup>
                </SelectContent>
              </FormSelect>
            )}
          />
```


without ScrollView :
<img width="413" alt="Screenshot 2024-08-23 at 3 04 11 PM" src="https://github.com/user-attachments/assets/82b31e00-816a-4add-95df-5e296feba7eb">

**Comment by useEffects** [comment]
> What do you mean? Form itself doesn't have a component. All the fields and such are in there (input, checkbox, radio). Forms don't have styles so I don't think I understand what you are looking for 😄

@RWOverdijk form component with these features https://ui.shadcn.com/docs/components/form#features

**Comment by RWOverdijk** [comment]
@useEffects Ah I see, right. I made my own, I don't use react-hook-form. But maybe there's a way to come up with something more generic.

**Comment by useEffects** [comment]
@RWOverdijk  I am trying to make use of https://github.com/vantezzen/auto-form
I only need form and calendar component now, thats the whole point of these 2 features requests :)

**Comment by mrzachnugent** [comment]
Hi @useEffects 

Due to a recent scope update this feature request is no longer within our current focus. See https://github.com/mrzachnugent/react-native-reusables/discussions/229, for more details.

Thanks for understanding!
