### ISSUE TITLE
[ FEATURE ] Need Calendar component

### ISSUE THREAD

**Issue by useEffects** [mrzachnugent/react-native-reusables#205]

**Comment by trevorpfiz** [comment]
@useEffects I recommend https://github.com/MarceloPrado/flash-calendar

**Comment by mrzachnugent** [comment]
Hi @useEffects 

Due to a recent scope update this feature request is no longer within our current focus. See https://github.com/mrzachnugent/react-native-reusables/discussions/229, for more details.

Thanks for understanding!
