### ISSUE TITLE
Development server won't start

### ISSUE THREAD

**Issue by Revaycolizer** [mrzachnugent/react-native-reusables#207]
I tried spinning my own expo project with react native reusables using bun but when I add a metro config.js file , development server stack at 64% and won't finish loading 

**Expected behavior**
Development server should start as always

**Comment by Revaycolizer** [comment]
> @Revaycolizer Sounds like a set-up issue. Can you please provide a minimal-reproduction repo?

Seems it's an issue with metro.config file in windows as in Ubuntu it works

**Comment by mrzachnugent** [comment]
Seems like its the same issue as https://github.com/mrzachnugent/react-native-reusables/issues/131
