### ISSUE TITLE
[ FEATURE ] use tailwind-buddy over CVA to handle responsivness

### ISSUE THREAD

**Issue by flozero** [mrzachnugent/react-native-reusables#236]
**Is your feature request related to a problem? Please describe.**
Let's say for the component [Button](https://rnr-docs.vercel.app/components/button/), base on the size of screen you want the button to change the size of it.

With the library you are using CVA. It's not possible as it doesn't handle responsive variants.

I was wondering if you would be interesting on using a library we are using inside my company to handle this case as it was not supported. https://github.com/busbud/tailwind-buddy

I would be happy to discuss with you about it. The other apis are really close to what CVA is doing so you won't be lost.

**Describe the solution you'd like**

Having to not handle responsive by having the same two components with just the same props but different values.

**Describe alternatives you've considered**

Using https://github.com/busbud/tailwind-buddy over CVA

**Comment by mrzachnugent** [comment]
@flozero Your library looks promising. However, in order to prevent steering away from shadcn we cannot add it unfortunately. 

You can add a post in the discussions section about it if you want.

**Comment by flozero** [comment]
Thank you :) will do and thanks for your work !
