### ISSUE TITLE
[ FEATURE ] Please Implement OTP Input

### ISSUE THREAD

**Issue by MarcusSanchez** [mrzachnugent/react-native-reusables#237]
**Is your feature request related to a problem? Please describe.**
It's really hard to implement a OTP by hand, it seems simple, but jumping inputs are actually somewhat tricky.

**Describe the solution you'd like**
Implementing shadcn/ui's OTP would be great.

**Comment by mrzachnugent** [comment]
Hey @MarcusSanchez, unfortunately this request fall out of this project's scope https://github.com/mrzachnugent/react-native-reusables?tab=readme-ov-file#project-scope

If you stumble upon a library or repository that implementing shadcn/ui's OTP for react-native, feel free to open a PR to add it to the list of Excluded Components
