### ISSUE TITLE
[ BUG ] Not all styles are being applied

### ISSUE THREAD

**Issue by GerardPolloRebozado** [mrzachnugent/react-native-reusables#238]
**Describe the bug**
I have a nx monorepo and I have been trying to install react native reusable to my app but the styles are not fully applied for example background color of the screen or borders are applied but background colors of button are not shown. using just nativwind works but not with the components

**Screenshots**
![image](https://github.com/user-attachments/assets/eb2c86de-69b2-4111-99d5-fe1793b30c5b)

```
import { useState } from 'react';
import { router } from 'expo-router';
import { Input } from '../components/ui/input';
import { Label } from '../components/ui/label';
import { useSession } from '../providers/useAuth';
import { View } from 'react-native';
import { Text } from '~/components/ui/text';
import { Button } from '~/components/ui/button';

export default function SignIn() {
    const { signIn } = useSession();
    const [email, setEmail] = useState('a@a.com');
    const [password, setPassword] = useState('123456aA');
    function send() {
        const res = signIn(email, password);
        router.push({ pathname: '/' });
    }
    return (
        <>
            <Text>Sign In</Text>
            <Label nativeID='email'>Email</Label>
            <Input nativeID='email' value={email} onChangeText={setEmail} />
            <Label nativeID='password'>Password</Label>
            <Input nativeID='password' value={password} onChangeText={setPassword} />
            <Button onPress={send}><Text>Sign in</Text></Button>
        </>
    );
}
```
**Additional context**
Im using nx to have a monorepo im not sure if the metro.config is correctrly configured:
```
const { withNxMetro } = require('@nx/expo');
const { getDefaultConfig } = require('@expo/metro-config');
const { withNativeWind } = require('nativewind/metro');
const { mergeConfig } = require('metro-config');

const defaultConfig = getDefaultConfig(__dirname);
const { assetExts, sourceExts } = defaultConfig.resolver;

/**
 * Metro configuration
 * https://reactnative.dev/docs/metro
 *
 * @type {import('metro-config').MetroConfig}
 */
const customConfig = {
  transformer: {
    babelTransformerPath: require.resolve('react-native-svg-transformer'),
  },
  resolver: {
    assetExts: assetExts.filter((ext) => ext !== 'svg'),
    sourceExts: [...sourceExts, 'cjs', 'mjs', 'svg'],
  },
};

module.exports = withNxMetro(mergeConfig(withNativeWind(defaultConfig, { input: './src/global.css' }), customConfig), {
  // Change this to true to see debugging info.
  // Useful if you have issues resolving modules
  debug: false,
  // all the file extensions used for imports other than 'ts', 'tsx', 'js', 'jsx', 'json'
  extensions: ['css'],
  // Specify folders to watch, in addition to Nx defaults (workspace libraries and node_modules)
  watchFolders: [],
});
```

**Comment by Enrique-Ambrocio** [comment]
Had a similar issue that I still haven't been able to resolve, but see if any of these solutions mentioned does the trick for you: https://github.com/mrzachnugent/react-native-reusables/issues/222

**Comment by GerardPolloRebozado** [comment]
> Had a similar issue that I still haven't been able to resolve, but see if any of these solutions mentioned does the trick for you: #222

thanks for the reply but that didnt work

**Comment by GerardPolloRebozado** [comment]
> Hey @GerardPolloRebozado Can you please provide a minimal reproduction repo?

Sure here you have a [repo](https://github.com/GerardPolloRebozado/testRNR)

**Comment by mrzachnugent** [comment]
@GerardPolloRebozado Unfortunately, I couldn't get the app running. I've never used nx and there are scripts or instructions on how to start the app.

I did notice that the version of NativeWind you are using is `4.0.1`, you should update it. That might be the cause of this issue.

You might also want to check https://www.nativewind.dev/v4/guides/troubleshooting.

Since this is an issue with NativeWind and Nx, unfortunately this is the most that I can help as it is not a react-native-reusables issue. Please consider reaching out to them for help. Best of luck!

**Comment by dehimer** [comment]
Up
