### ISSUE TITLE
[ BUG ] Starter Base Installation Results in Blank Simulator

### ISSUE THREAD

**Issue by Mahesh-Vegiraju** [mrzachnugent/react-native-reusables#241]
**Describe the bug**
I tried to make a fresh install today using the Starter Base installation but I end up with a white screen on the iOS simulator and on my phone using the Expo Go app. I am not sure if its because I am doing something wrong, but I tried it multiple times and made sure to follow the instructions to the T. 

**To Reproduce**
1. Follow the steps to download the starter base project
2. Run npm run ios
3. See the blank app on the simulator

**Screenshots**
<img width="1488" alt="Screenshot 2024-09-13 at 8 44 08 PM" src="https://github.com/user-attachments/assets/15694348-2cf0-4df7-b5e1-ff4f5024390c">

**Platform (please complete the following information):**
 - Type: iOS 17.5 iPhone 15 pro simulator, macbook pro 16 2019

**Comment by G4lile00** [comment]
Same issue on android, tried to fix, but no result

**Comment by 4ver** [comment]
Same on both ios and android

**Comment by mrzachnugent** [comment]
The issue seems to be with the NativeWind version. With a fresh install, it installs version `4.1.9`. I got it to work by changing it to `"nativewind": "4.1.7",` in the package.json then re-installing the dependencies.

**Comment by mrzachnugent** [comment]
I opened an issue for NativeWind's repo https://github.com/nativewind/nativewind/issues/1072

**Comment by mrzachnugent** [comment]
Fixed in nativewind version `4.1.10`
