### ISSUE TITLE
[ BUG ] icon color defaulting to blue if using cn helper with conditional

### ISSUE THREAD

**Issue by trevorpfiz** [mrzachnugent/react-native-reusables#242]
**Describe the bug**
this works:
```
<RefreshCw
            className="text-foreground"
            size={24}
          />
```

this breaks the `text-foreground`:
```
<RefreshCw
            className={cn("text-foreground", isSyncPending && "animate-spin")}
            size={24}
          />
```

**To Reproduce**
1. Use an iconWithClassName with a conditional
2. See error

**Expected behavior**
I would expect the `text-foreground` to be applied and styles not to break when using a conditional.

**Platform (please complete the following information):**
 - Type: iPhone 14 Pro Max
 - OS: iOS

**Additional context**
I can work on a repro soon. Thanks!

**Comment by mrzachnugent** [comment]
@trevorpfiz From a quick look, I think the "animate-spin" class might be the issue. In the `iconWithClassName` function, only `color` and `opacity` are cssInteroped. 

What is you tried:
```tsx
<View className={cn(isSyncPending && "animate-spin")}
  <RefreshCw className={cn("text-foreground")} size={24} />
</View>
```
Or update the `iconWithClassName` to accept animate-spin (I'm not sure how to do that)?

**Comment by trevorpfiz** [comment]
> @trevorpfiz From a quick look, I think the "animate-spin" class might be the issue. In the `iconWithClassName` function, only `color` and `opacity` are cssInteroped.
> 
> What if you tried:
> 
> ```tsx
> <View className={cn(isSyncPending && "animate-spin")}
>   <RefreshCw className={cn("text-foreground")} size={24} />
> </View>
> ```
> 
> Or update the `iconWithClassName` to accept animate-spin (I'm not sure how to do that)?

that works! thanks!

**Comment by trevorpfiz** [comment]
actually, this is not working on `"nativewind": "4.1.6"`. not sure what allowed it to work before?

```
Error: Couldn't find a navigation context. Have you wrapped your app with 'NavigationContainer'? See https://reactnavigation.org/docs/getting-started for setup instructions.

This error is located at:
    in CssInterop.View (created by HomeHeader)
```

**Comment by mrzachnugent** [comment]
@trevorpfiz To my knowledge, the newest version of NativeWind is `4.1.10`. Can you try that?

**Comment by trevorpfiz** [comment]
> @trevorpfiz To my knowledge, the newest version of NativeWind is `4.1.10`. Can you try that?

It gives the same error. You can see in this repro: https://github.com/trevorpfiz/starter-base-repro

**Comment by mrzachnugent** [comment]
@trevorpfiz This is a NativeWind bug, could you update your repro repo to have the `View` with the `animate-spin` class name uncommented and remove the `cn` function? So just `<View className="animate-spin">` and open an issue in the NativeWind repo with a link to your repro?

Closing this issue as it's a case that is not used in react-native-reusables and it is a NativeWind bug.
