### ISSUE TITLE
[ BUG ] Button Text color doesn't change regardless of the current theme

### ISSUE THREAD

**Issue by musab-olurode** [mrzachnugent/react-native-reusables#244]
**Describe the bug**
Button Text color remains black in both light and dark theme WITHOUT changing anything. It looks like the `text-foreground` class has no effect in the button TextContext. Adding any other non-theme text color works as expected. This exists on the starter-base without any modifications.

**To Reproduce**
1. Create a new project as instructed in the README
2. Install dependencies
3. Start the app on android and or web
4. Buton Text remains black in both themes 

**Expected behavior**
Button Text should use the defined foreground color in dark mode

**Screenshots**
![image](https://github.com/user-attachments/assets/7dfad7e1-091b-463d-86d4-d027008ee5e5)

**Platform (please complete the following information):**
 - Type: Android Emulator
 - OS: [e.g. iOS] Android 13
 - Browser: Arc, Firefox for windows

**Additional context**

**Comment by musab-olurode** [comment]
Additionally, simple tailwind animations on icons are broken. 
![rnr-bug](https://github.com/user-attachments/assets/2bfb7692-2f61-4f3d-80e3-85fe3a840db0)
Inspecting the generated HTML in the browser, it looks like all classes are being added to the SVG icons and all their children
![image](https://github.com/user-attachments/assets/35600eb3-9faa-4df0-bc8a-1180567b6c25)

**Comment by archodev** [comment]
Nativewind animations are still experimental

**Comment by musab-olurode** [comment]
> Nativewind animations are still experimental

I was using it fine in a previous version of rnr though.

**Comment by musab-olurode** [comment]
> But also experiencing the same button text issue, it is fixed if you make the color a hex instead of hsl

That doesn't break nativewind?

**Comment by archodev** [comment]
I just tested this again and that trick no longer works, for now what does work is on the custom text view putting `dark:text-white`

**Comment by trevorpfiz** [comment]
@musab-olurode is this in the latest versions of NativeWind? `4.1.6` works for me, but after that `text-foreground` seems to be breaking.

**Comment by musab-olurode** [comment]
@trevorpfiz I've tested with `4.0.33` (the preinstalled version on the starter base) and `4.0.36`

**Comment by musab-olurode** [comment]
@trevorpfiz I just tried 4.16, still doesn't work.

**Comment by trevorpfiz** [comment]
@mrzachnugent You can see `text-foreground` not setting a color on the button text when it is inside a `Card`. I am noticing this bug in different project, where it seems all uses of `text-foreground` within a `Card` are not working. `4.1.6` is the latest version without the bug. repro: https://github.com/trevorpfiz/starter-base-repro

![text-foreground-bug-in-card](https://github.com/user-attachments/assets/4f68c4de-c5b1-4de4-bc5f-bc9109e97264)

**Comment by eli-front** [comment]
Still seeing this

**Comment by memresahin** [comment]
+1

**Comment by oocmoe** [comment]
`import { Text } from "react-native` ✖
`import { Text } from "~/components/ui/text` ✔
