### ISSUE TITLE
[ BUG ] Select component rendering just emply black border input , on clicking it, gives error inifinitely

### ISSUE THREAD

**Issue by aqib-real** [mrzachnugent/react-native-reusables#245]
This is the error I am getting infinitely on clicking select component, which is rendered as empty black border input box

Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.
    in ContentNativeSelect (created by ContentNativeSelect)
    in RCTView (created by View)
    in View (created by AnimatedComponent(View))
    in AnimatedComponent(View)
    in Unknown (created by ContentNativeSelect)
    in RCTView (created by View)
    in View (created by Pressable)
    in Pressable (created by Pressable)
    in OverlayNativeSelect (created by ContentNativeSelect)
    in PortalHost (created by RootLayout)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by RootLayout)
    in RootLayout
    in Unknown (created by Route())
    in Suspense (created by Route())
    in Route (created by Route())
    in Route() (created by ContextNavigator)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by wrapper)
    in wrapper (created by ContextNavigator)
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainerInner (created by ContextNavigator)
    in ContextNavigator (created by ExpoRoot)
    in ExpoRoot (created by App)
    in App (created by ErrorOverlay)
    in ErrorToastContainer (created by ErrorOverlay)
    in ErrorOverlay (created by withDevTools(ErrorOverlay))
    in withDevTools(ErrorOverlay)
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in main(RootComponent)

**Comment by mrzachnugent** [comment]
@aqib-real Please provide a minimal reproduction repo and make sure you are using the latest version of NativeWind

**Comment by aqib-real** [comment]
Thanks @mrzachnugent , I am not sure how to do that but I will try to update NativeWind and see if the issue is resolved, I'll let you know anyway.

**Comment by aqib-real** [comment]
updating nativewind resolved the issue , thanks Zach.
