### ISSUE TITLE
DropDown menu type mismatch

### ISSUE THREAD

**Issue by ImamJanjua** [mrzachnugent/react-native-reusables#246]
I wanted to implement a dropdown menu in my app but noticed that the DropdownMenuRadioItem was not indicating which option was currently selected, even though I was passing the controlled values to it. After checking the documentation, I found that the dropdown radio-related components were supposed to accept a boolean, and the onValueChange was also expected to return a boolean. However, in my code, the value was expecting a string, and onValueChange was returning the selected radio item's value as a string. I downloaded the latest version of the dropdown menu, but it’s still receiving a string, which seems more appropriate to me than a boolean, despite what the documentation suggests. 
<img width="1000" alt="Screenshot 2024-09-19 at 21 30 42" src="https://github.com/user-attachments/assets/7030f9bf-1e59-418e-9ff5-2c55fb345d52">
<img width="631" alt="Screenshot 2024-09-19 at 21 31 15" src="https://github.com/user-attachments/assets/bb1d7b67-1609-4372-8183-4560ef407bf6">

**Comment by mrzachnugent** [comment]
@ImamJanjua Thanks for contributing! The fix can be found in the commit above this comment.
