### ISSUE TITLE
[ BUG ] Buttons do not change Text color properly.

### ISSUE THREAD

**Issue by Redoxahmii** [mrzachnugent/react-native-reusables#247]
**Describe the bug**
The Text colors are not working properly when using different variants.

**To Reproduce**
1. Copy your Starter-base example and turn to dark mode.

**Expected behavior**
Should change to `foreground` text color properly.

**Screenshots**
![t_2024_09_22_08_32](https://github.com/user-attachments/assets/9bffc9ea-3ed3-45d9-a49e-18c2c6551fdf)
Nothings changed from the starter-base repo.

**Platform (please complete the following information):**
Android.
LInux.

**Additional context**

**Comment by trevorpfiz** [comment]
https://github.com/mrzachnugent/react-native-reusables/issues/244#issuecomment-2362307327

**Comment by mrzachnugent** [comment]
Seems like a NativeWind issue so I created one: https://github.com/nativewind/nativewind/issues/1114

**Comment by koutyuke** [comment]
Apparently this is caused by a css variable being passed, but the value is `null`.

**Comment by koutyuke** [comment]
Also, this seems to happen with components defined elsewhere (in node_modules or monopore workspace) than in `tailwind.config.js` at the root of the project.

**Comment by mrzachnugent** [comment]
https://github.com/nativewind/nativewind/issues/1114#issuecomment-2403949948

**Comment by eli-front** [comment]
still seeing this
