### ISSUE TITLE
Button doesn't work correctly when the `onPress` changes.

### ISSUE THREAD

**Issue by trentcharlie** [mrzachnugent/react-native-reusables#25]
This is documenting an issue that my team and I have also been experiencing working with `Pressable`. In the example below, one would expect the `Pressable` and `Button` to behave exactly the same. Each incrementing the `counter` when pressed but when you run the sample you'll notice that the `Button` initially increments the counter to `1` and then stops while the `Pressable` always increments. You'll also notice that the `Pressable` also stops working properly when we add any of `active:*`, `hover:*` or `group`. The issue seems to be a bug in nativewind and might be caused by lack of handling of the `onPress` prop change.

**Potential fix**
Until the issue is addressed in nativewind it might be tricky to address but I suppose one approach would be to avoid using `active:*`, `hover:*` or `group` and instead opt for the `({pressed})` properties passed if you use a function as a child in the `Pressable`.

```tsx
import { useState } from "react";
import { Pressable, Text, View } from "react-native";
import { Button } from "~/components/universal-ui/button";

export default function ExampleScreen() {
  const [count, setCount] = useState(0);
  return (
    <View className="gap-5 flex-1 justify-center px-5">
      <Button onPress={() => setCount(count + 1)}>
        <Text>Count: {count}</Text>
      </Button>
      <Pressable
        // Roughly styled
        className="bg-primary px-4 items-center justify-center h-10 rounded-md"
        onPress={() => setCount(count + 1)}
      >
        <Text>Count: {count}</Text>
      </Pressable>
    </View>
  );
}
```

**Comment by trentcharlie** [comment]
I've got the same version:
```
"node_modules/nativewind": {
      "version": "4.0.13",
      "resolved": "https://registry.npmjs.org/nativewind/-/nativewind-4.0.13.tgz",
      "integrity": "sha512-iLbilVaeCabUcuNaRquSD76TC0LggZKPIeUlG5q3P5wNvMYuET6kn4OKZDaWxC5kpIOO323HYJHCj8DCg3E1Pw==",
      "dependencies": {
        "react-native-css-interop": "0.0.13"
      },
      "engines": {
        "node": ">=16"
      },
      "peerDependencies": {
        "tailwindcss": ">3.3.0"
      }
    },
```

**Comment by trentcharlie** [comment]
> If you check the [progress example](https://github.com/mrzachnugent/react-native-reusables/blob/main/app/(main)/progress/progress-universal.tsx), it is using a button with an onPress to update the state.

I this is consistent with the observation. Adding this to the `onPress` should produce the same issue.

```
Toast.show({
      type: "base",
      text1: "Heads up!",
      text2: `Current progress: ${progress}`,
 });
```
I believe the toast is always gonna show `Current progress: 13`

**Comment by mrzachnugent** [comment]
I see.

Unfortunately, this seems to be `NativeWind` issue:

- https://github.com/marklawlor/nativewind/issues/740
- https://github.com/marklawlor/nativewind/issues/233

If you are updating state from it's previous state, a workaround is to update your state like this:

```js
 setCount((prev) => prev + 1);
 ```

Keeping this issue open until solution is implemented.

**Comment by trentcharlie** [comment]
Yeah, it's a nativewind issue

**Comment by mrzachnugent** [comment]
Fixed with:
- Updating Nativewind to v.4.0.31 https://github.com/mrzachnugent/react-native-reusables/commit/8efd9881f69ac0f565930ee1d330708629f0c00c
- Removing workaround code and add back group and active classNames
