### ISSUE TITLE
[ BUG ] I am simply unable to access the document page.

### ISSUE THREAD

**Issue by Teamplatedev** [mrzachnugent/react-native-reusables#251]
**Describe the bug**
I’m sorry, this is not a bug or an error, but rather, I have simply been unable to access the document page (https://rnr-docs.vercel.app/) for the past few days. It might be that the page has exceeded its usage limit on the Vercel hosting service, or perhaps it’s just me experiencing this issue. I find this project extremely useful for React Native developers, so I hope it continues to be well-maintained. Thank you.

**To Reproduce**
1. Start the '...' app with '...'
2. Go to '...'

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
 - Type: [eg: Browser, Simulator, Emulator, Device]
 - Browser (if applies) [e.g. chrome, safari]

**Additional context**

**Comment by Teamplatedev** [comment]
Ah sorry for it. Just, The country I stay blocked the domain(vercel.app) Never mind. It's a communism country lol

**Comment by mrzachnugent** [comment]
@Teamplatedev Good luck with that
