### ISSUE TITLE
[ BUG ] Dialog not closes on outside click, close button not working.

### ISSUE THREAD

**Issue by kerimovok** [mrzachnugent/react-native-reusables#254]

**Comment by mrzachnugent** [comment]
Hey @kerimovok, please provide a minimal reproduction repo as I am unable to reproduce this issue.

**Comment by kerimovok** [comment]
Steps to reproduce:
1. Create Expo project
2. Add the Dialog component manually as shown in docs for native only
3. Add code example from docs and test on mobile device

I tried some props on DialogOverlay, but still not working, close button also not working

Tested on:
iOS 17
iPhone X

Thank you for project

**Comment by kaumac** [comment]
This (click outside to close) is actually not working on the demo page:
[https://rnr-showcase.vercel.app/alert-dialog](https://rnr-showcase.vercel.app/alert-dialog)

Also there's no close/exit animation, curious if this is a limitation of the implementation or if its a bug

**Comment by mrzachnugent** [comment]
@kaumac That is desired behaviour. See https://ui.shadcn.com/docs/components/alert-dialog for reference. As for the animations, it seems like a bug.

**Comment by kaumac** [comment]
thanks for clarifying that @mrzachnugent 

The animation issue seems to be project wide. The same happens with the tooltip component. I'll create a separate issue for this.
