### ISSUE TITLE
[ BUG ] Expo crashes when web and ios used simultaneously 

### ISSUE THREAD

**Issue by slavagoreev** [mrzachnugent/react-native-reusables#255]
**Describe the bug**
App crashes after opening the same page using web and ios app.

**To Reproduce**
1. Start with `pnpm run dev:showcase` using the latest committed version of rnr
2. Go to 'Alert Dialog' page on web and click
2. Go to 'Alert Dialog' page on ios app
3. See error
```
 WARN  [Reanimated] No animation was provided for the sequence 
 Invariant Violation: Rotate transform must be expressed in degrees (deg) or radians (rad): {"rotate":"initial"}
```

**Expected behavior**
No error

**Screenshots**
<img width="1227" alt="image" src="https://github.com/user-attachments/assets/f09a63c3-ff40-4ec2-b23f-cfeb4dff2abf">

https://github.com/user-attachments/assets/c96433c6-b379-4604-a234-e1185e61163f

**Platform (please complete the following information):**
 - Type: All
 - OS: All
 - Browser (if applies): Chrome

**Additional context**
Tried clearing all node_modules, .expo and etc. Fresh install recreates the same error

**Comment by mrzachnugent** [comment]
Hey @slavagoreev, to my knowledge, this is a NativeWind bug. I work on either mobile or web at one time to prevent this from happening.

Could you create a minimal reproduction repo and create an issue in the NativeWind repo with it attached?

**Comment by mrzachnugent** [comment]
Closed as assumed the issue was opened in the NativeWind repo
