### ISSUE TITLE
[ BUG ] Starter-Base build using "eas build" gets stuck after [RUN_GRADLEW] Done writing sourcemap output

### ISSUE THREAD

**Issue by Muhammad-The-Conqueror** [mrzachnugent/react-native-reusables#257]
**Describe the bug**
the starter base works fine on expo go but when building for android it stops at
[RUN_GRADLEW] Done writing bundle output
[RUN_GRADLEW] Done writing sourcemap output

**To Reproduce**
1. Clone starter-base
2. run "npm i"
2. run "eas build --local"
3. Choose Android

**Additional context**
I think the problem has something to do with importing global.css into _layout.tsx . the app build just fine if you remove that import but the consequence of that is losing all the styles

**Comment by mrzachnugent** [comment]
@Muhammad-The-Conqueror Might be this https://github.com/nativewind/nativewind/issues/1150

**Comment by Muhammad-The-Conqueror** [comment]
It appears to be the same issue. i tried downgrading nativewind to v4.1.10 then v4.1.7 then v4.1.0
but with no luck

**Comment by fisher0fm3n** [comment]
I'm facing the same issue, initially I was using v4.0.1 and still ran into this

**Comment by Muhammad-The-Conqueror** [comment]
@fisher0fm3n I reverted back to "nativewind": "^4.1.10" then followed the instructions in the comment mentioned above.
the build completed successfully and there is no issue with the styling.
thanks everyone @mrzachnugent @fisher0fm3n.
