### ISSUE TITLE
[ BUG ] Latest CLI Cant install components

### ISSUE THREAD

**Issue by jwhughes-work** [mrzachnugent/react-native-reusables#260]
**Describe the bug**
Installing components using:  `npx @react-native-reusables/cli@latest add radio-group.` No longer works since the release of cli@0.1.1

![error](https://github.com/user-attachments/assets/585b7433-4199-476e-bc4e-1c106c457ce1)

Using the newest version I get the error above, however if I use cli@0.1.0 all works fine, I'm not sure if its something I have missed or need to change for the latest version. Or if it is indeed a bug

**Expected behavior**
Install component, which works on the previous version of cli within my project

**Platform (please complete the following information):**
 - VS Code

**Comment by mattmatters** [comment]
Getting the same over here:

```
{
  "platforms": "universal",
  "aliases": {
    "components": "~/components",
    "lib": "~/lib"
  }
}
```

**Comment by mattmatters** [comment]
Looks like a result of https://github.com/mrzachnugent/react-native-reusables/commit/743f58d7a0cf19b94da3afad4d2b742210334381. Is there a changelog anywhere? Love all the improvements but having trouble finding anything documenting them + any breaking changes.

**Comment by mrzachnugent** [comment]
Just published the fix. 

@mattmatters There isn't a changelog yet. Haven't gotten around to it. If that's something you'd like to add, PRs are welcomed.

**Comment by mattmatters** [comment]
> Just published the fix.
> 
> @mattmatters There isn't a changelog yet. Haven't gotten around to it. If that's something you'd like to add, PRs are welcomed.

Thanks for being so prompt. Let me see if I can get something going. Definitely would like to give back to this project in some way.

**Comment by jwhughes-work** [comment]
Thanks for being so quick @mrzachnugent ! loving the project also :)
