### ISSUE TITLE
[ FEATURE ] shadcn like CLI for adding components.

### ISSUE THREAD

**Issue by Jan-Eckerlein** [mrzachnugent/react-native-reusables#262]
Could you imagine a shadcn like cli for adding components?
With a config file to define where the components would be added?

**Comment by mrzachnugent** [comment]
Hey @Jan-Eckerlein 
Like `npx @react-native-reusables/cli@latest add button`?

You can use it today. For more info checkout: https://github.com/mrzachnugent/react-native-reusables/tree/main/packages/cli#react-native-reusables-cli
