### ISSUE TITLE
[ BUG ] Not able to change or modify css using tailwind

### ISSUE THREAD

**Issue by samarthasthan** [mrzachnugent/react-native-reusables#271]
**Describe the bug**
I'm using your starter pack, so integration shouldn't be an issue. However, I've encountered this problem multiple times. Whenever I try to use or modify one of your components, it doesn't work as expected. I'm not sure why this is happening. I've attached a screenshot below for your reference.
(Here:- I am using text-black to make text color black but its not working)

**Expected behavior**
We should be able to modify components to suit our needs.

**Screenshots**
![image](https://github.com/user-attachments/assets/99079eeb-1743-474e-a8c4-ef2f7b8c3daa)
![image](https://github.com/user-attachments/assets/ae6d8dcb-3297-480a-ac3b-febdcdc83986)

**Platform (please complete the following information):**
 - Type: [Smart Phone]
 - OS: [iOS 18]

**Comment by mrzachnugent** [comment]
Hey @samarthasthan could you please provide a minimal reproduction repo and make sure it is using the latest version of NativeWind?

**Comment by samarthasthan** [comment]
@mrzachnugent , Here is Link - https://github.com/samarthasthan/shadcn-react-native, please read the README file, i have mentioned the problems there.

**Comment by mrzachnugent** [comment]
@samarthasthan Your index file has a `jsx` extension. By switching the file name  to  `index.tsx`, it fixes your issue.

<img width="450" alt="Screenshot 2024-11-01 at 2 53 25 PM" src="https://github.com/user-attachments/assets/61467ab9-df66-491e-9141-9d91155e6e5b">

**Comment by samarthasthan** [comment]
@mrzachnugent but why text above button is not rendering ?

**Comment by mrzachnugent** [comment]
@samarthasthan It's because of the `flex-1` className in your` <View className="flex-1 gap-3">` component at line 17. This is due to how styling is done in react-native. If you were to use the same styles using the StyleSheet instead of NativeWind, you would have the same issue.

As a solution, you can either add `flex-1` to the `SafeAreaView` or remove it from the `View` mentioned above.

**Comment by samarthasthan** [comment]
Facing same issue, it does not work at all, i am not understanding why its so in consistence and unpredictable. 

```
import React from "react";
import { SafeAreaView } from "react-native-safe-area-context";
import { View, TouchableOpacity } from "react-native";
import { Text } from "~/components/ui/text";
import { Input } from "~/components/ui/input";
import { Button } from "~/components/ui/button";
import { Separator } from "~/components/ui/separator";

const SignInPage = () => {
  return (
    <SafeAreaView className="flex-1 justify-center px-4">
      <View className="items-center mb-6">
        <Text className="text-3xl font-bold">Instagram</Text>
      </View>
      <View className="space-y-4">
        <View>
          <Text className="mb-2">Email or Phone</Text>
          <Input placeholder="Email or Phone Number" />
        </View>

        <View>
          <Text className="mb-2">Password</Text>
          <Input placeholder="Password" secureTextEntry />
        </View>

        <TouchableOpacity className="self-end">
          <Text className="text-blue-500 mt-2">Forgot Password?</Text>
        </TouchableOpacity>

        <Button className="mt-4">
          <Text>Sign In</Text>
        </Button>
      </View>

      <View className="my-6">
        <Separator />
      </View>

      <View className="flex-row justify-center space-x-2">
        <Text>Don't have an account?</Text>
        <TouchableOpacity>
          <Text className="font-bold text-blue-500">Sign Up</Text>
        </TouchableOpacity>
      </View>
    </SafeAreaView>
  );
};

export default SignInPage;

```

**Comment by mrzachnugent** [comment]
@samarthasthan This is what I see when I copied your code in your reproduction repo:

<img width="440" alt="Screenshot 2024-11-01 at 9 35 33 PM" src="https://github.com/user-attachments/assets/b9db3168-2aef-4781-85f5-a5decffd972e">

What's missing?
