### ISSUE TITLE
[ BUG ] What the different between pnpm and yarn in project contain rnr library

### ISSUE THREAD

**Issue by lockhaicttv** [mrzachnugent/react-native-reusables#285]
Hi RNR team,

I am using this package for my project. My problem is the showcase in your source code works perfectly from the text to the UI, for each feature your team demos. But the start-base has some problems:

1. The text is not responsive and sometimes overflows the button or card
2. Bottom sheet and datepicker code copy from showcase not working, when click on the button the bottom sheet view is not showing
3. I don't know why the showcase works perfectly with the pnpm meanwhile the startbase crashes, and notifies some bug when starting with pnpm. Start with yarn or npm work but they give me the feeling different with the showcase
4. I am confused about setup source code with pnpm workspace like the showcase is a better approach than starbase?

I love this package and want it to grow strongly in the future, thanks for answering these questions.

Best regards

P/s: I got this error when try to start project with pnpm
![image](https://github.com/user-attachments/assets/f7863877-d937-4fcd-8164-dd30a72d478f)

**Comment by mrzachnugent** [comment]
Hey @lockhaicttv,

1. Is the behaviour different from using the StyleStheet, or is it behaviour that you would expect like the web? There is a [feature request](https://github.com/mrzachnugent/react-native-reusables/issues/219) that already exists. If you are talking about a bug that does not happen with StyleSheet, can you create a separate issue.
2. Bottom sheet and date picker are deprecated components and do not work for the web. They are out the the current [project's scope](https://github.com/mrzachnugent/react-native-reusables/discussions/229) for the time being.
3. This monorepo is setup with pnpm-workspace which means that it will only work out of the box with pnpm. 
4. For now, the suggested way to start a project is with the [start-base instructions](https://rnr-docs.vercel.app/getting-started/initial-setup/), then to use the [CLI](https://github.com/mrzachnugent/react-native-reusables/tree/main/apps/cli#react-native-reusables-cli) to add the components you need. We will work on improving this.

For your error, I would need a minimal reproduction repo to look into it. So if you still have this issue with react-native-reusables, please open another issue.
