### ISSUE TITLE
[ BUG ] material-top-tabs Rendering Issue in Development Build

### ISSUE THREAD

**Issue by surya123866** [mrzachnugent/react-native-reusables#287]
**Describe the bug**
  The top tabs are not functioning properly in the development build when using Expo. However, they work as expected when using  Expo Go.

**To Reproduce**
1. Start the app in the development build environment of Expo.
2. Render the Material Top Tabs screen .
2. Attempt to render the screen or switch between tabs.
3. Observe the following error in the UI: "viewManagerResolver returned null for either RNSVGPath or RCTRNSVGPath".

**Expected behavior**
  The top tabs should function in the development build the same way they do when using Expo Go.

**Screenshots**
![Screenshot_2024-12-01-14-31-58-07_0733b93f6536edfbb992ed797651f64a](https://github.com/user-attachments/assets/a1b6eeeb-a10d-465e-8948-462fffecd9a4)

**Platform (please complete the following information):**
 - Type: Device
 - OS: Android
 - React Native : 0.76
 - Expo SDK: 52

**Additional context**
   The issue occurs only in the development build; within expo go works normally.

**Comment by Rinwaoluwa** [comment]
@surya123866 were you able to find a solution to this bug i'm currently experiencing it

**Comment by surya123866** [comment]
> @surya123866 were you able to find a solution to this bug i'm currently experiencing it

verify the package exist or not npx expo install 
@react-navigation/material-top-tabs react-native-tab-view react-native-pager-view

**Comment by Rinwaoluwa** [comment]
> > @surya123866 were you able to find a solution to this bug i'm currently experiencing it
> 
> Please verify whether the following packages exist:
> 
> @react-navigation/material-top-tabs react-native-tab-view react-native-pager-view
> 
> Also, update Expo and React Native. Rebuild and run the project again.
> 
> This might resolve the issue. I'm not entirely sure how it was resolved for me, but it's currently working fine.

Thank you, But I have fixed it the issue was related to react-native-svg native modules not linking correctly. Rebuilding the project and reinstalling the APK ensured the changes were applied.

**Comment by Code-Divine** [comment]
Having this exact same issue except that I don't have any linking issue. Custom expo build, all plugins above installed and to latest version, react native latest etc

**Comment by surya123866** [comment]
> > > @surya123866 were you able to find a solution to this bug i'm currently experiencing it
> > 
> > 
> > Please verify whether the following packages exist:
> > @react-navigation/material-top-tabs react-native-tab-view react-native-pager-view
> > Also, update Expo and React Native. Rebuild and run the project again.
> > This might resolve the issue. I'm not entirely sure how it was resolved for me, but it's currently working fine.
> 
> Thank you, But I have fixed it the issue was related to react-native-svg native modules not linking correctly. Rebuilding the project and reinstalling the APK ensured the changes were applied.

It's not really an issue with react-native-svg. I used to encounter the issue while rendering material-top-tabs, and when I removed it, everything started working. You should find out exactly which component or library is causing the issue.
