### ISSUE TITLE
Question about fonts

### ISSUE THREAD

**Issue by Arsenii-Zhelobetskyi** [mrzachnugent/react-native-reusables#289]
Where can i found fonts. It's seems that this library uses some fonts, but i'm having hard time trying to found where is some config or whatever

**Comment by toy-crane** [comment]
I'm experiencing the same problem too

**Comment by toy-crane** [comment]
I solved it by referencing this code
https://github.com/mrzachnugent/react-native-reusables/blob/main/apps/showcase/app/_layout.tsx

**Comment by mrzachnugent** [comment]
Each platform has their own system fonts that they come with: [Android](https://developer.android.com/reference/kotlin/androidx/glance/text/FontFamily#public-companion-properties_1) and [iOS](https://developer.apple.com/fonts/system-fonts/). For web, it depends per machine. 

You can use [expo-fonts](https://docs.expo.dev/develop/user-interface/fonts/) to add a custom font. 

Whether you want to use a custom font or a system font, you can modify the tailwind.config.js to select the fonts: https://www.nativewind.dev/blog/announcement-nativewind-v4#new-fontfamily-defaults
