### ISSUE TITLE
Proposal: theme manager

### ISSUE THREAD

**Issue by ahmadbakhshi** [mrzachnugent/react-native-reusables#48]
I was thinking of making a base theme object to contain all the styling for all elements. So I can change some elements since I am not crazy about theming and design.

Currently it's tightly coupled with logic and makes it difficult for any future updates. And as a developer, I don't want to start completely from scratch,  I just want to update, or add new variants or etc.

By having it separate as a base theme, we could still have styled components with separation of concern and the most important part, developers can always extend the theme. Like what is currently happening in [@mui/material](https://mui.com/material-ui/customization/theme-components/#theme-style-overrides) which makes it super convenient to override default values globally.

Proposal: 
A base theme object that contains all existing styles, along with a theme extension function that gives you an existing theme as an argument and ability to override an existing one, or add new variants without changing anything in components/ui folder.

I would be happy to work on a PR.

**Comment by mrzachnugent** [comment]
@ahmadbakhshi Not sure what you mean exactly. 

Could you provide a real example?

You can override styles by changing/providing a `className`. Not sure, if you're talking about something else.

- In your `~/components/ui/button`, in the `buttonVariants`, you can provide different className. 
Ex: `bg-red-500 rounded-xl`
- Or wherever you use the Button component, you can add a className which will override the base styling.
Ex: `<Button className="bg-green-500 rounded-none"><Text>Press Me</Text></Button>`

**Comment by ahmadbakhshi** [comment]
this is completely fine if you want to update few thing, but what if you want to create a whole new design system but still extend from existing theme as base theme?

Then you should update every file in your ui folder. If a new update or bug fix release, you should update files one by one and make sure to apply you style which is not a pleasant experience. I had similar issue with shadcn/ui.

If we abstract the base theme into an object, them we can update only one file which is going to be our SSOT

Example:

```ts

export const baseTheme = {
  button: {
    root: {
      base: 'group flex items-center justify-center rounded-md web:ring-offset-background web:transition-colors web:focus-visible:outline-none web:focus-visible:ring-2 web:focus-visible:ring-ring web:focus-visible:ring-offset-2',
      variant: {
        default: 'bg-primary web:hover:opacity-90 active:opacity-90',
        destructive: 'bg-destructive web:hover:opacity-90 active:opacity-90',
        outline:
          'border border-input bg-background web:hover:bg-accent web:hover:text-accent-foreground active:bg-accent',
        secondary: 'bg-secondary web:hover:opacity-80 active:opacity-80',
        ghost: 'web:hover:bg-accent web:hover:text-accent-foreground active:bg-accent',
        link: 'web:underline-offset-4 web:hover:underline web:focus:underline ',
      },
      size: {
        default: 'h-10 px-4 py-2 native:h-12 native:px-5 native:py-3',
        sm: 'h-9 rounded-md px-3',
        lg: 'h-11 rounded-md px-8 native:h-14',
        icon: 'h-10 w-10',
      },
      defaultVariants: {
        variant: 'default',
        size: 'default',
      } as const,
    },
    text: {
      base: 'web:whitespace-nowrap text-sm native:text-base font-medium text-foreground web:transition-colors',
      variant: {
        default: 'text-primary-foreground',
        destructive: 'text-destructive-foreground',
        outline: 'group-active:text-accent-foreground',
        secondary: 'text-secondary-foreground group-active:text-secondary-foreground',
        ghost: 'group-active:text-accent-foreground',
        link: 'text-primary group-active:underline',
      },
      size: {
        default: '',
        sm: '',
        lg: 'native:text-lg',
        icon: '',
      },
      defaultVariants: {
        variant: 'default',
        size: 'default',
      } as const,
    },
  },
  dialog: {
    // root:...
    // root:...
  },
};



type BaseTheme = typeof baseTheme;

type ArgsType = {
  button: (t: BaseTheme['button']) => Partial<BaseTheme['button']>;
  dialog: (t: BaseTheme['dialog']) => Partial<BaseTheme['dialog']>;
};

export function createTheme(args: Partial<ArgsType>): BaseTheme {
  return {
    button: { ...baseTheme.button, ...args.button },
    dialog: { ...baseTheme.dialog, ...args.dialog },
  };
}

export const myTheme = createTheme({
  button: (t) => ({
    root: { variant: {...t.root.variants, myNewVariant: 'my config' } },
    text: { defaultVariants: { newDefault: true } },
  }),
});

```


// ~components/ui/button.tsx

```tsx
import { cva, type VariantProps } from 'class-variance-authority';
import * as React from 'react';
import { Pressable } from 'react-native';
import { TextClassContext } from '../../components/ui/typography';
import { cn } from '../../lib/utils';
import { baseTheme, myTheme } from '../theme-manager';
import { twMerge } from 'tailwind-merge';

const buttonVariants = cva(twMerge(baseTheme.button.root.base, myTheme.button.root.base), {
  variants: {
    variant: Object.assign(baseTheme.button.root.variant, myTheme.button.root.variant),
    size: Object.assign(baseTheme.button.root.size, myTheme.button.root.variant),
  },
  defaultVariants: Object.assign(
    baseTheme.button.root.defaultVariants,
    baseTheme.button.root.defaultVariants
  ),
});

const buttonTextVariants = cva(twMerge(baseTheme.button.text.base, myTheme.button.text.base), {
  variants: {
    variant: Object.assign(baseTheme.button.text.variant, myTheme.button.text.variant),
    size: Object.assign(baseTheme.button.text.size, myTheme.button.text.size),
  },
  defaultVariants: Object.assign(
    baseTheme.button.text.defaultVariants,
    myTheme.button.text.defaultVariants
  ),
});

type ButtonProps = React.ComponentPropsWithoutRef<typeof Pressable> &
  VariantProps<typeof buttonVariants>;

const Button = React.forwardRef<React.ElementRef<typeof Pressable>, ButtonProps>(
  ({ className, variant, size, ...props }, ref) => {
    return (
      <TextClassContext.Provider
        value={cn(
          props.disabled && 'web:pointer-events-none',
          buttonTextVariants({ variant, size: size as any })
        )}
      >
        <Pressable
          className={cn(
            props.disabled && 'opacity-50 web:pointer-events-none',
            buttonVariants({ variant, size, className })
          )}
          ref={ref}
          role='button'
          {...props}
        />
      </TextClassContext.Provider>
    );
  }
);
Button.displayName = 'Button';

export { Button, buttonTextVariants, buttonVariants };
export type { ButtonProps };
```

**Comment by mrzachnugent** [comment]
@ahmadbakhshi 

Unfortunately, this is not how it is done in [ui/shadcn](https://ui.shadcn.com/) so I cannot add this to the project.

For this project, the idea of the "base theme" should be a starting point and you should change it for your project. It is suggested to remove the className from the components in the `ui` that you don't use and replace them with the classNames you actually use. I would not suggest keeping the "base theme" classNames that you do not use. 

Then, if you need to change classNames in a specific case, you should add a className.

For updating CSS variables, NativeWind offers a way to do so: https://www.nativewind.dev/v4/guides/themes#dynamic-themes

Thank you for your suggestion. Nothing is stopping you from using a theme manager it in your project 😊
