### ISSUE TITLE
Dark mode only works on first launch.

### ISSUE THREAD

**Issue by salvinoto** [mrzachnugent/react-native-reusables#50]
Hi, I setup dark mode exactly like the docs say, and it only works when I first launch the app. Switching back and fourth doesnt work. I am using iOS simulator. Any idea why?

**Comment by mrzachnugent** [comment]
Maybe this could help: https://github.com/marklawlor/nativewind/issues/702

If it doesn't, you can re-open a new issue. Please include a link to a minimal reproduction repo.

Thanks
