### ISSUE TITLE
react-strict-dom for universal UI

### ISSUE THREAD

**Issue by fatihsever** [mrzachnugent/react-native-reusables#51]
Yesterday, Meta added a new repository called [react-strict-dom](https://github.com/facebook/react-strict-dom). This library aims to improve and standardize the development of styled React components for web and native. It is still an experimental library, but it has a lot of promise: https://twitter.com/Baconbrix/status/1760327319892234280

I think it might be useful to build the universal UI of react-native-reusables on top of this in the future. Thanks.

**Comment by fatihsever** [comment]
It seems that the Microsoft React Native team is also investing in this project:
https://twitter.com/Kelset/status/1760367655423549480

**Comment by mrzachnugent** [comment]
@fatihsever Yes, it looks super promising. However, it is experimental and not ready for production.

If you would like to discuss more about it, please open a new discussion in the discussion section.

**Comment by fatihsever** [comment]
Sure. I missed the discussion section, sorry. Thanks.
