### ISSUE TITLE
[ FEATURE ] Creating a bottom drawer.

### ISSUE THREAD

**Issue by Zaid-Abdalkarim** [mrzachnugent/react-native-reusables#96]
**Is your feature request related to a problem? Please describe.**
There is no bottom sheet for this project, and it seems that almost every application that I build now requires one of these.

**Describe the solution you'd like**
Creating a bottom drawer like this one here.
https://github.com/gorhom/react-native-bottom-sheet

**Describe alternatives you've considered**
https://github.com/gorhom/react-native-bottom-sheet
I've considered this one and will still use it, but it'd be amazing to have one from the reusables project.

**Comment by atanaskanchev** [comment]
> Hey @Zaid-Abdalkarim,
> 
> 
> 
> There is a bottom-sheet in the deprecated-ui: https://github.com/mrzachnugent/react-native-reusables/blob/main/packages/reusables/src/components/deprecated-ui/bottom-sheet.native.tsx. However, it is not yet implemented for web.
> 
> 
> 
> I will work on it after I am finished the first draft of the documentation.
> 
> 
> 
> Hope this helps!
> 
> 
> 
> 

There's some great native only components in hi-deprecated. Would you be interested in releasing them as native-only packages? Not all apps are universal so they will definitely get adopted

**Comment by mrzachnugent** [comment]
@atanaskanchev Good question.

So `deprecated-ui` is a little hidden but it is there for people to use. In the README, all component screenshots/video are for the deprecated-ui.

In the [Backlog](https://github.com/mrzachnugent/react-native-reusables?tab=readme-ov-file#backlog) of the README, I plan on improving the remaining component from `deprecated-ui`, making them universal, and add it to the `ui` components.

For those that only want to use it for Native, there is a Native Only option for copy/pasting and I will continue to do so. For example, in the alert-dialog primitive, in the installation instruction, there is a tab where you can select `Universal` or `Native Only`: https://rnr-docs.vercel.app/primitives/alert-dialog/#installation
