### ISSUE TITLE
'@rnr/accordion@*' is not in this registry.

### ISSUE THREAD

**Issue by CanArslanDev** [mrzachnugent/react-native-reusables#97]
**Describe the bug**
Hello,
When I want to run the application in the apps>showcase directory in the repository, I get an error in every package that starts with @rnr on package.json.

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@rnr%2faccordion - Not found
npm ERR! 404 
npm ERR! 404  '@rnr/accordion@*' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**To Reproduce**
1. Open the 'apps/showcase' app
2. Type 'npm i' in terminal

**Expected behavior**
Downloads npm packages without any problems

**Screenshots**
<img width="594" alt="image" src="https://github.com/mrzachnugent/react-native-reusables/assets/76579053/ffac8fc7-50df-48bf-bb37-7064580dafc2">

**Platform (please complete the following information):**
 - Type: Emulator
 - OS: Android API 30

**Comment by BehlulAy** [comment]
Hello @CanArslanDev  I have same problem.

Any solutions yet?

**Comment by mrzachnugent** [comment]
To fix the ` '@rnr/accordion@*' is not in this registry.` issue, you have to install the deps in the root of the monorepo and you have to use `pnpm` to avoid conflicts in the `lock` files.

1. If you ran `npm i` in apps/showcase, delete the `package-lock.json` and the `node_modules`.
2. Change directories into the root folder (`cd ../../`)
3. Run `pnpm i` ([install pnpm](https://pnpm.io/installation) if you do not already have it on your machine)

There is also an existing issue https://github.com/mrzachnugent/react-native-reusables/issues/95 about android development that I have not looked into yet. 

Let me know if you if run into the other issue after you resolve the ` '@rnr/accordion@*' is not in this registry.` issue

**Comment by CanArslanDev** [comment]
Thank you @mrzachnugent , this solution work on windows!
